# Importing required modules
import PyQt5
from PyQt5.QtWidgets import *
from PyQt5.QtCore import *
from PyQt5.QtGui import *
from PyQt5 import sip
from PyQt5 import QtCore, QtGui, QtWidgets


import sys
import os


class settingsUI(QWidget):

    def __init__(self, parent):
        super().__init__(parent)
        self.gridLayout = QtWidgets.QGridLayout(self)
        self.gridLayout.setSpacing(11)
        self.gridLayout.setObjectName("gridLayout")

        self.startingPIn = QtWidgets.QLineEdit(self)
        font = QtGui.QFont()
        font.setFamily("Figtree Light")
        font.setPointSize(11)
        self.startingPIn.setFont(font)
        self.startingPIn.setObjectName("startingPIn")
        self.gridLayout.addWidget(self.startingPIn, 5, 3, 1, 1)

        self.subsetSizeIn = QtWidgets.QLineEdit(self)
        font = QtGui.QFont()
        font.setFamily("Figtree Light")
        font.setPointSize(11)
        self.subsetSizeIn.setFont(font)
        self.subsetSizeIn.setObjectName("subsetSizeIn")
        self.gridLayout.addWidget(self.subsetSizeIn, 2, 1, 1, 1)
        self.stepSizeLab = QtWidgets.QLabel(self)
        font = QtGui.QFont()
        font.setFamily("Figtree Light")
        font.setPointSize(11)
        self.stepSizeLab.setFont(font)
        self.stepSizeLab.setObjectName("stepSizeLab")
        self.gridLayout.addWidget(self.stepSizeLab, 3, 0, 1, 1)

        self.label_9 = QtWidgets.QLabel(self)
        font = QtGui.QFont()
        font.setFamily("Figtree Light")
        font.setPointSize(11)
        self.label_9.setFont(font)
        self.label_9.setObjectName("label_9")
        self.gridLayout.addWidget(self.label_9, 5, 2, 1, 1)

        self.refStartLab = QtWidgets.QLabel(self)
        font = QtGui.QFont()
        font.setFamily("Figtree Light")
        font.setPointSize(11)
        self.refStartLab.setFont(font)
        self.refStartLab.setObjectName("refStartLab")
        self.gridLayout.addWidget(self.refStartLab, 4, 0, 1, 1)
        self.subsetSizeLab = QtWidgets.QLabel(self)
        font = QtGui.QFont()
        font.setFamily("Figtree Light")
        font.setPointSize(11)
        self.subsetSizeLab.setFont(font)
        self.subsetSizeLab.setObjectName("subsetSizeLab")
        self.gridLayout.addWidget(self.subsetSizeLab, 2, 0, 1, 1)
        self.dicTypeBox = QtWidgets.QComboBox(self)
        font = QtGui.QFont()
        font.setFamily("Figtree Light")
        font.setPointSize(11)
        self.dicTypeBox.setFont(font)
        self.dicTypeBox.setObjectName("dicTypeBox")
        self.dicTypeBox.addItem("")
        self.gridLayout.addWidget(self.dicTypeBox, 0, 1, 1, 1)
        self.maxIterLab = QtWidgets.QLabel(self)
        font = QtGui.QFont()
        font.setFamily("Figtree Light")
        font.setPointSize(11)
        self.maxIterLab.setFont(font)
        self.maxIterLab.setObjectName("maxIterLab")
        self.gridLayout.addWidget(self.maxIterLab, 1, 2, 1, 1)
        self.stepSizeIn = QtWidgets.QLineEdit(self)
        font = QtGui.QFont()
        font.setFamily("Figtree Light")
        font.setPointSize(11)
        self.stepSizeIn.setFont(font)
        self.stepSizeIn.setObjectName("stepSizeIn")
        self.gridLayout.addWidget(self.stepSizeIn, 3, 1, 1, 1)
        self.refBox = QtWidgets.QComboBox(self)
        font = QtGui.QFont()
        font.setFamily("Figtree Light")
        font.setPointSize(11)
        self.refBox.setFont(font)
        self.refBox.setObjectName("refBox")
        self.refBox.addItem("")
        self.refBox.addItem("")
        self.gridLayout.addWidget(self.refBox, 4, 1, 1, 1)
        self.maxItIn = QtWidgets.QLineEdit(self)
        font = QtGui.QFont()
        font.setFamily("Figtree Light")
        font.setPointSize(11)
        self.maxItIn.setFont(font)
        self.maxItIn.setObjectName("maxItIn")
        self.gridLayout.addWidget(self.maxItIn, 1, 3, 1, 1)

        self.convergenceIn = QtWidgets.QLineEdit(self)
        font = QtGui.QFont()
        font.setFamily("Figtree Light")
        font.setPointSize(11)
        self.convergenceIn.setFont(font)
        self.convergenceIn.setObjectName("convergenceIn")
        self.gridLayout.addWidget(self.convergenceIn, 2, 3, 1, 1)

        self.znccTolIn = QtWidgets.QLineEdit(self)
        font = QtGui.QFont()
        font.setFamily("Figtree Light")
        font.setPointSize(11)
        self.znccTolIn.setFont(font)
        self.znccTolIn.setObjectName("znccTolIn")
        self.gridLayout.addWidget(self.znccTolIn, 3, 3, 1, 1)

        self.interpOrderIn = QtWidgets.QLineEdit(self)
        font = QtGui.QFont()
        font.setFamily("Figtree Light")
        font.setPointSize(11)
        self.interpOrderIn.setFont(font)
        self.interpOrderIn.setObjectName("interpOrderIn")
        self.gridLayout.addWidget(self.interpOrderIn, 4, 3, 1, 1)

        self.shapeFuncLab = QtWidgets.QLabel(self)
        font = QtGui.QFont()
        font.setFamily("Figtree Light")
        font.setPointSize(11)
        self.shapeFuncLab.setFont(font)
        self.shapeFuncLab.setObjectName("shapeFuncLab")
        self.gridLayout.addWidget(self.shapeFuncLab, 1, 0, 1, 1)
        self.dicTypeLab = QtWidgets.QLabel(self)
        font = QtGui.QFont()
        font.setFamily("Figtree Light")
        font.setPointSize(11)
        self.dicTypeLab.setFont(font)
        self.dicTypeLab.setObjectName("dicTypeLab")
        self.gridLayout.addWidget(self.dicTypeLab, 0, 0, 1, 1)
        self.algoTypeBox = QtWidgets.QComboBox(self)
        font = QtGui.QFont()
        font.setFamily("Figtree Light")
        font.setPointSize(11)
        self.algoTypeBox.setFont(font)
        self.algoTypeBox.setObjectName("algoTypeBox")
        self.algoTypeBox.addItem("")
        self.algoTypeBox.addItem("")
        self.algoTypeBox.addItem("")
        self.gridLayout.addWidget(self.algoTypeBox, 0, 3, 1, 1)

        self.converLab = QtWidgets.QLabel(self)
        font = QtGui.QFont()
        font.setFamily("Figtree Light")
        font.setPointSize(11)
        self.converLab.setFont(font)
        self.converLab.setObjectName("converLab")
        self.gridLayout.addWidget(self.converLab, 2, 2, 1, 1)

        self.znccTolLab = QtWidgets.QLabel(self)
        font = QtGui.QFont()
        font.setFamily("Figtree Light")
        font.setPointSize(11)
        self.znccTolLab.setFont(font)
        self.znccTolLab.setObjectName("znccTolLab")
        self.gridLayout.addWidget(self.znccTolLab, 3, 2, 1, 1)

        self.interpOrderLab = QtWidgets.QLabel(self)
        font = QtGui.QFont()
        font.setFamily("Figtree Light")
        font.setPointSize(11)
        self.interpOrderLab.setFont(font)
        self.interpOrderLab.setObjectName("interpOrderLab")
        self.gridLayout.addWidget(self.interpOrderLab, 4, 2, 1, 1)

        self.shapeFuncBox = QtWidgets.QComboBox(self)
        font = QtGui.QFont()
        font.setFamily("Figtree Light")
        font.setPointSize(11)
        self.shapeFuncBox.setFont(font)
        self.shapeFuncBox.setObjectName("shapeFuncBox")
        self.shapeFuncBox.addItem("")
        self.shapeFuncBox.addItem("")
        self.gridLayout.addWidget(self.shapeFuncBox, 1, 1, 1, 1)
        self.algorLab = QtWidgets.QLabel(self)
        font = QtGui.QFont()
        font.setFamily("Figtree Light")
        font.setPointSize(11)
        self.algorLab.setFont(font)
        self.algorLab.setObjectName("algorLab")
        self.gridLayout.addWidget(self.algorLab, 0, 2, 1, 1)
        self.stepSizeLab.setText("Step Size:")
        self.label_9.setText("Starting Points:")
        self.refStartLab.setText("Reference Strategy")
        self.refBox.setItemText(0, "Relative")
        self.refBox.setItemText(1, "Absolute")
        self.subsetSizeLab.setText("Subset Size:")
        self.dicTypeBox.setItemText(0, "Planar")
        self.maxIterLab.setText("Max Iterations:")
        self.shapeFuncLab.setText("Shape Function")
        self.dicTypeLab.setText("DIC Type")
        self.converLab.setText("Convergence:")
        self.znccTolLab.setText("ZNCC Tolerance:")
        self.interpOrderLab.setText("Interpolation Order:")
        self.shapeFuncBox.setItemText(0, "Affine")
        self.shapeFuncBox.setItemText(1, "Quadratic")
        self.algorLab.setText("Algorithm")
        self.algoTypeBox.setItemText(0, "IC-GN")
        self.algoTypeBox.setItemText(1, "IC-LM")
        self.algoTypeBox.setItemText(2, "Fast-IC-LM")


class imageSetUi(QWidget):
    def __init__(self, parent):
        super().__init__(parent)

        self.verticalLayout = QtWidgets.QVBoxLayout(self)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.folderLab = QtWidgets.QLabel(self)
        sizePolicy = QtWidgets.QSizePolicy(
            QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(
            self.folderLab.sizePolicy().hasHeightForWidth())
        self.folderLab.setSizePolicy(sizePolicy)
        self.folderLab.setMaximumSize(QtCore.QSize(16777215, 28))
        font = QtGui.QFont()
        font.setFamily("Figtree Light")
        font.setPointSize(11)
        self.folderLab.setFont(font)
        self.folderLab.setObjectName("folderLab")
        self.horizontalLayout.addWidget(self.folderLab)
        self.folderDisp = QtWidgets.QLabel(self)
        sizePolicy = QtWidgets.QSizePolicy(
            QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(
            self.folderDisp.sizePolicy().hasHeightForWidth())
        self.folderDisp.setSizePolicy(sizePolicy)
        self.folderDisp.setMaximumSize(QtCore.QSize(16777215, 28))
        font = QtGui.QFont()
        font.setFamily("Figtree Light")
        font.setPointSize(11)
        self.folderDisp.setFont(font)
        self.folderDisp.setFrameShape(QtWidgets.QFrame.Panel)
        self.folderDisp.setFrameShadow(QtWidgets.QFrame.Plain)
        self.folderDisp.setObjectName("folderDisp")
        self.horizontalLayout.addWidget(self.folderDisp)
        self.selFolderBut = QtWidgets.QPushButton(self)
        self.selFolderBut.setMaximumSize(QtCore.QSize(93, 28))
        font = QtGui.QFont()
        font.setFamily("Figtree Light")
        font.setPointSize(11)
        self.selFolderBut.setFont(font)
        self.selFolderBut.setObjectName("selFolderBut")
        self.horizontalLayout.addWidget(self.selFolderBut)
        self.verticalLayout.addLayout(self.horizontalLayout)
        spacerItem = QtWidgets.QSpacerItem(
            20, 10, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        self.verticalLayout.addItem(spacerItem)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setContentsMargins(0, -1, -1, -1)
        self.gridLayout.setHorizontalSpacing(7)
        self.gridLayout.setVerticalSpacing(4)
        self.gridLayout.setObjectName("gridLayout")
        self.startIn = QtWidgets.QLineEdit(self)
        self.startIn.setMinimumSize(QtCore.QSize(0, 22))
        self.startIn.setMaximumSize(QtCore.QSize(82, 22))
        self.startIn.setBaseSize(QtCore.QSize(8, 8))
        font = QtGui.QFont()
        font.setFamily("Figtree Light")
        font.setPointSize(11)
        self.startIn.setFont(font)
        self.startIn.setText("")
        self.startIn.setMaxLength(50)
        self.startIn.setObjectName("startIn")
        self.gridLayout.addWidget(self.startIn, 0, 1, 1, 1, QtCore.Qt.AlignTop)
        self.startLab = QtWidgets.QLabel(self)
        font = QtGui.QFont()
        font.setFamily("Figtree Light")
        font.setPointSize(11)
        self.startLab.setFont(font)
        self.startLab.setObjectName("startLab")
        self.gridLayout.addWidget(
            self.startLab, 0, 0, 1, 1, QtCore.Qt.AlignLeft | QtCore.Qt.AlignTop)
        self.endIn = QtWidgets.QLineEdit(self)
        self.endIn.setMaximumSize(QtCore.QSize(82, 22))
        self.endIn.setBaseSize(QtCore.QSize(8, 8))
        font = QtGui.QFont()
        font.setFamily("Figtree Light")
        font.setPointSize(11)
        self.endIn.setFont(font)
        self.endIn.setText("")
        self.endIn.setObjectName("endIn")
        self.gridLayout.addWidget(self.endIn, 1, 1, 1, 1, QtCore.Qt.AlignTop)
        self.incIn = QtWidgets.QLineEdit(self)
        self.incIn.setMaximumSize(QtCore.QSize(82, 22))
        self.incIn.setBaseSize(QtCore.QSize(8, 8))
        font = QtGui.QFont()
        font.setFamily("Figtree Light")
        font.setPointSize(11)
        self.incIn.setFont(font)
        self.incIn.setText("")
        self.incIn.setObjectName("incIn")
        self.gridLayout.addWidget(self.incIn, 2, 1, 1, 1, QtCore.Qt.AlignTop)
        self.endLab = QtWidgets.QLabel(self)
        font = QtGui.QFont()
        font.setFamily("Figtree Light")
        font.setPointSize(11)
        self.endLab.setFont(font)
        self.endLab.setObjectName("endLab")
        self.gridLayout.addWidget(
            self.endLab, 1, 0, 1, 1, QtCore.Qt.AlignLeft | QtCore.Qt.AlignTop)
        self.incLab = QtWidgets.QLabel(self)
        font = QtGui.QFont()
        font.setFamily("Figtree Light")
        font.setPointSize(11)
        self.incLab.setFont(font)
        self.incLab.setObjectName("incLab")
        self.gridLayout.addWidget(
            self.incLab, 2, 0, 1, 1, QtCore.Qt.AlignLeft | QtCore.Qt.AlignTop)
        spacerItem1 = QtWidgets.QSpacerItem(
            40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem1, 0, 2, 1, 1)
        self.setMax = QtWidgets.QToolButton(self)
        font = QtGui.QFont()
        font.setFamily("Figtree Light")
        font.setPointSize(8)
        self.setMax.setFont(font)
        self.setMax.setObjectName("setMax")
        self.gridLayout.addWidget(self.setMax, 1, 2, 1, 1)
        self.horizontalLayout_2.addLayout(self.gridLayout)
        self.imagesLab = QtWidgets.QLabel(self)
        font = QtGui.QFont()
        font.setFamily("Figtree Light")
        font.setPointSize(11)
        self.imagesLab.setFont(font)
        self.imagesLab.setObjectName("imagesLab")
        self.horizontalLayout_2.addWidget(
            self.imagesLab, 0, QtCore.Qt.AlignTop)
        self.dispImages = QtWidgets.QListView(self)
        self.dispImages.setMaximumSize(QtCore.QSize(16777215, 90))
        self.dispImages.setBaseSize(QtCore.QSize(250, 250))
        font = QtGui.QFont()
        font.setFamily("Figtree Light")
        font.setPointSize(11)
        self.dispImages.setFont(font)
        self.dispImages.setHorizontalScrollBarPolicy(
            QtCore.Qt.ScrollBarAsNeeded)
        self.dispImages.setResizeMode(QtWidgets.QListView.Adjust)
        self.dispImages.setObjectName("dispImages")
        self.horizontalLayout_2.addWidget(
            self.dispImages, 0, QtCore.Qt.AlignTop)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        spacerItem2 = QtWidgets.QSpacerItem(
            20, 10, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        self.verticalLayout.addItem(spacerItem2)
        self.groupBox = QtWidgets.QGroupBox(self)
        self.groupBox.setEnabled(True)
        sizePolicy = QtWidgets.QSizePolicy(
            QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(
            self.groupBox.sizePolicy().hasHeightForWidth())
        self.groupBox.setSizePolicy(sizePolicy)
        self.groupBox.setMinimumSize(QtCore.QSize(0, 90))
        self.groupBox.setMaximumSize(QtCore.QSize(16777215, 90))
        font = QtGui.QFont()
        font.setFamily("Figtree Light")
        font.setPointSize(11)
        self.groupBox.setFont(font)
        self.groupBox.setFlat(False)
        self.groupBox.setObjectName("groupBox")
        self.gridLayoutWidget = QtWidgets.QWidget(self.groupBox)
        self.gridLayoutWidget.setGeometry(QtCore.QRect(0, 10, 671, 81))
        self.gridLayoutWidget.setObjectName("gridLayoutWidget")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.gridLayoutWidget)
        self.gridLayout_2.setSizeConstraint(QtWidgets.QLayout.SetNoConstraint)
        self.gridLayout_2.setContentsMargins(0, 12, 0, 0)
        self.gridLayout_2.setObjectName("gridLayout_2")
        spacerItem3 = QtWidgets.QSpacerItem(
            40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_2.addItem(spacerItem3, 0, 2, 1, 1)
        self.gausLab = QtWidgets.QLabel(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setFamily("Figtree Light")
        font.setPointSize(11)
        self.gausLab.setFont(font)
        self.gausLab.setObjectName("gausLab")
        self.gridLayout_2.addWidget(self.gausLab, 0, 0, 1, 1)
        self.backIn = QtWidgets.QLineEdit(self.gridLayoutWidget)
        self.backIn.setMaximumSize(QtCore.QSize(82, 22))
        self.backIn.setBaseSize(QtCore.QSize(8, 8))
        font = QtGui.QFont()
        font.setFamily("Figtree Light")
        font.setPointSize(11)
        self.backIn.setFont(font)
        self.backIn.setObjectName("backIn")
        self.gridLayout_2.addWidget(self.backIn, 1, 1, 1, 1)
        self.gausIn = QtWidgets.QLineEdit(self.gridLayoutWidget)
        self.gausIn.setMaximumSize(QtCore.QSize(82, 22))
        self.gausIn.setBaseSize(QtCore.QSize(8, 8))
        font = QtGui.QFont()
        font.setFamily("Figtree Light")
        font.setPointSize(11)
        self.gausIn.setFont(font)
        self.gausIn.setObjectName("gausIn")
        self.gridLayout_2.addWidget(self.gausIn, 0, 1, 1, 1)
        self.backLab = QtWidgets.QLabel(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setFamily("Figtree Light")
        font.setPointSize(11)
        self.backLab.setFont(font)
        self.backLab.setObjectName("backLab")
        self.gridLayout_2.addWidget(self.backLab, 1, 0, 1, 1)
        self.verticalLayout.addWidget(self.groupBox)
        self.defaultsBut = QtWidgets.QPushButton(self)
        font = QtGui.QFont()
        font.setFamily("Figtree Light")
        font.setPointSize(11)
        self.defaultsBut.setFont(font)
        self.defaultsBut.setObjectName("defaultsBut")
        self.verticalLayout.addWidget(self.defaultsBut)
        spacerItem4 = QtWidgets.QSpacerItem(
            20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem4)
        spacerItem5 = QtWidgets.QSpacerItem(
            20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem5)

        self.folderLab.setText("Folder:")
        self.folderDisp.setText("PATH to Images...")
        self.selFolderBut.setText("File Select")
        self.startLab.setText("Start:")
        self.endLab.setText("End:")
        self.incLab.setText("Increment:")
        self.setMax.setText("Set Max")
        self.imagesLab.setText("Images")
        self.groupBox.setTitle("Advanced Settings")
        self.gausLab.setText("Gaussian Blur:")
        self.backLab.setText("Background/Cutoff:")
        self.defaultsBut.setText("Defaults")


class roiDefUi(QWidget):
    def __init__(self, parent):
        super().__init__(parent)
        self.verticalLayout = QtWidgets.QVBoxLayout(self)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setSpacing(0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setSpacing(0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.checkBox = QtWidgets.QCheckBox(self)
        self.checkBox.setObjectName("checkBox")
        self.horizontalLayout.addWidget(self.checkBox)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setHorizontalSpacing(25)
        self.gridLayout.setVerticalSpacing(6)
        self.gridLayout.setObjectName("gridLayout")
        self.widthDisp = QtWidgets.QLabel(self)
        self.widthDisp.setEnabled(False)
        font = QtGui.QFont()
        font.setFamily("Figtree Light")
        font.setPointSize(11)
        self.widthDisp.setFont(font)
        self.widthDisp.setObjectName("widthDisp")
        self.gridLayout.addWidget(self.widthDisp, 0, 2, 1, 1)
        self.heightDisp = QtWidgets.QLabel(self)
        self.heightDisp.setEnabled(False)
        font = QtGui.QFont()
        font.setFamily("Figtree Light")
        font.setPointSize(11)
        self.heightDisp.setFont(font)
        self.heightDisp.setObjectName("heightDisp")
        self.gridLayout.addWidget(self.heightDisp, 1, 2, 1, 1)
        self.topLeftyDisp = QtWidgets.QLabel(self)
        self.topLeftyDisp.setEnabled(False)
        font = QtGui.QFont()
        font.setFamily("Figtree Light")
        font.setPointSize(11)
        self.topLeftyDisp.setFont(font)
        self.topLeftyDisp.setObjectName("topLeftyDisp")
        self.gridLayout.addWidget(self.topLeftyDisp, 0, 0, 1, 1)
        self.xIn = QtWidgets.QLineEdit(self)
        self.xIn.setEnabled(False)
        font = QtGui.QFont()
        font.setFamily("Figtree Light")
        font.setPointSize(11)
        self.xIn.setFont(font)
        self.xIn.setObjectName("xIn")
        self.gridLayout.addWidget(self.xIn, 0, 1, 1, 1)
        self.topLeftxDisp = QtWidgets.QLabel(self)
        self.topLeftxDisp.setEnabled(False)
        font = QtGui.QFont()
        font.setFamily("Figtree Light")
        font.setPointSize(11)
        self.topLeftxDisp.setFont(font)
        self.topLeftxDisp.setObjectName("topLeftxDisp")
        self.gridLayout.addWidget(self.topLeftxDisp, 1, 0, 1, 1)
        self.yIn = QtWidgets.QLineEdit(self)
        self.yIn.setEnabled(False)
        font = QtGui.QFont()
        font.setFamily("Figtree Light")
        font.setPointSize(11)
        self.yIn.setFont(font)
        self.yIn.setObjectName("yIn")
        self.gridLayout.addWidget(self.yIn, 1, 1, 1, 1)
        self.widthIn = QtWidgets.QLineEdit(self)
        self.widthIn.setEnabled(False)
        font = QtGui.QFont()
        font.setFamily("Figtree Light")
        font.setPointSize(11)
        self.widthIn.setFont(font)
        self.widthIn.setObjectName("widthIn")
        self.gridLayout.addWidget(self.widthIn, 0, 3, 1, 1)
        self.heightIn = QtWidgets.QLineEdit(self)
        self.heightIn.setEnabled(False)
        font = QtGui.QFont()
        font.setFamily("Figtree Light")
        font.setPointSize(11)
        self.heightIn.setFont(font)
        self.heightIn.setObjectName("heightIn")
        self.gridLayout.addWidget(self.heightIn, 1, 3, 1, 1)
        self.verticalLayout.addLayout(self.gridLayout)
        spacerItem = QtWidgets.QSpacerItem(
            20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        self.verticalLayout.addItem(spacerItem)
        self.checkBox.setText("Enter Manually")
        self.widthDisp.setText("Width:")
        self.heightDisp.setText("Height:")
        self.topLeftyDisp.setText("Top Left x:")
        self.topLeftxDisp.setText("Top Left y:")


class analysisUi(QWidget):
    def __init__(self, parent):
        super().__init__(parent)
        self.verticalLayout = QtWidgets.QVBoxLayout(self)
        self.verticalLayout.setContentsMargins(6, 6, 6, 6)
        self.verticalLayout.setSpacing(0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setContentsMargins(-1, -1, -1, 5)
        self.gridLayout.setHorizontalSpacing(10)
        self.gridLayout.setVerticalSpacing(7)
        self.gridLayout.setObjectName("gridLayout")
        self.cpuLab = QtWidgets.QLabel(self)
        font = QtGui.QFont()
        font.setFamily("Figtree Light")
        font.setPointSize(11)
        self.cpuLab.setFont(font)
        self.cpuLab.setObjectName("cpuLab")
        self.gridLayout.addWidget(self.cpuLab, 1, 0, 1, 1)
        self.debugIn = QtWidgets.QComboBox(self)
        sizePolicy = QtWidgets.QSizePolicy(
            QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(
            self.debugIn.sizePolicy().hasHeightForWidth())
        self.debugIn.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Figtree Light")
        font.setPointSize(11)
        self.debugIn.setFont(font)
        self.debugIn.setObjectName("debugIn")
        self.gridLayout.addWidget(self.debugIn, 0, 1, 1, 1)
        self.debugLab = QtWidgets.QLabel(self)
        font = QtGui.QFont()
        font.setFamily("Figtree Light")
        font.setPointSize(11)
        self.debugLab.setFont(font)
        self.debugLab.setObjectName("debugLab")
        self.gridLayout.addWidget(self.debugLab, 0, 0, 1, 1)
        self.cpuIn = QtWidgets.QLineEdit(self)
        sizePolicy = QtWidgets.QSizePolicy(
            QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(
            self.cpuIn.sizePolicy().hasHeightForWidth())
        self.cpuIn.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Figtree Light")
        font.setPointSize(11)
        self.cpuIn.setFont(font)
        self.cpuIn.setObjectName("cpuIn")
        self.gridLayout.addWidget(self.cpuIn, 1, 1, 1, 1)
        spacerItem = QtWidgets.QSpacerItem(
            40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem, 0, 2, 1, 1)
        spacerItem1 = QtWidgets.QSpacerItem(
            40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem1, 1, 2, 1, 1)
        self.verticalLayout.addLayout(self.gridLayout)
        self.progOut = QtWidgets.QTextEdit(self)
        sizePolicy = QtWidgets.QSizePolicy(
            QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(
            self.progOut.sizePolicy().hasHeightForWidth())
        self.progOut.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Figtree Light")
        font.setPointSize(13)
        self.progOut.setFont(font)
        self.progOut.setFrameShape(QtWidgets.QFrame.Box)
        self.progOut.setFrameShadow(QtWidgets.QFrame.Plain)
        self.progOut.setLineWidth(1)
        self.progOut.setReadOnly(True)
        self.progOut.setObjectName("progOut")
        self.verticalLayout.addWidget(self.progOut)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        spacerItem2 = QtWidgets.QSpacerItem(
            40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem2)
        self.statusLab = QtWidgets.QLabel(self)
        font = QtGui.QFont()
        font.setFamily("Figtree Light")
        font.setPointSize(11)
        self.statusLab.setFont(font)
        self.statusLab.setObjectName("statusLab")
        self.horizontalLayout_2.addWidget(self.statusLab)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.startBut = QtWidgets.QPushButton(self)
        font = QtGui.QFont()
        font.setFamily("Figtree Light")
        font.setPointSize(11)
        self.startBut.setFont(font)
        self.startBut.setObjectName("startBut")
        self.horizontalLayout.addWidget(self.startBut)

        self.killBut = QtWidgets.QPushButton(self)
        font = QtGui.QFont()
        font.setFamily("Figtree Light")
        font.setPointSize(11)
        self.killBut.setFont(font)
        self.killBut.setObjectName("killBut")
        self.horizontalLayout.addWidget(self.killBut)

        spacerItem3 = QtWidgets.QSpacerItem(
            40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem3)
        self.verticalLayout.addLayout(self.horizontalLayout)

        self.cpuLab.setText("CPU Count:")
        self.debugLab.setText("Debug Level")
        self.statusLab.setText("Status:")
        self.startBut.setText("Start")
        self.killBut.setText("Stop")


class resultsUi(QWidget):
    def __init__(self, parent):
        super().__init__(parent)
        self.mainVLayout = QtWidgets.QVBoxLayout(self)
        self.mainVLayout.setContentsMargins(0, 0, 0, 0)
        self.mainVLayout.setSpacing(4)
        self.mainVLayout.setObjectName("mainVLayout")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setSpacing(0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.textBut = QtWidgets.QPushButton(self)
        font = QtGui.QFont()
        font.setFamily("Figtree Light")
        font.setPointSize(11)
        self.textBut.setFont(font)
        self.textBut.setStyleSheet("    QPushButton{\n"
                                   "        border: 2px  solid  rgb(0, 0, 0);\n"
                                   "        background: rgb(255, 255, 255);\n"
                                   "        border-style: outset;\n"
                                   "        border-width: 1px 1px 1px 1px;\n"
                                   "        border-radius: 0px;\n"
                                   "        color: black;\n"
                                   "        padding: 5px 5px 5px 5px;   \n"
                                   "    }\n"
                                   "QPushButton:checked {\n"
                                   "border-style: inset;\n"
                                   "background: qradialgradient(\n"
                                   "cx: 0.4, cy: -0.1, fx: 0.4, fy: -0.1,\n"
                                   "radius: 1.35, stop: 0 #fff, stop: 1 #90D5FF\n"
                                   ");\n"
                                   "}\n"
                                   "QPushButton:disabled {\n"
                                   "border-style: outset;\n"
                                   "background: qradialgradient(\n"
                                   "cx: 0.4, cy: -0.1, fx: 0.4, fy: -0.1,\n"
                                   "radius: 1.35, stop: 0 #fff, stop: 1 #ddd\n"
                                   ");\n"
                                   "}\n"
                                   "")
        self.textBut.setCheckable(True)
        self.textBut.setAutoExclusive(True)
        self.textBut.setObjectName("textBut")
        self.horizontalLayout.addWidget(self.textBut)
        self.contBut = QtWidgets.QPushButton(self)
        font = QtGui.QFont()
        font.setFamily("Figtree Light")
        font.setPointSize(11)
        self.contBut.setFont(font)
        self.contBut.setStyleSheet("    QPushButton{\n"
                                   "        border: 2px  solid  rgb(0, 0, 0);\n"
                                   "        background: rgb(255, 255, 255);\n"
                                   "        border-style: outset;\n"
                                   "        border-width: 1px 1px 1px 0px;\n"
                                   "        border-radius: 0px;\n"
                                   "        color: black;\n"
                                   "        padding: 5px 5px 5px 5px;   \n"
                                   "    }\n"
                                   "QPushButton:checked {\n"
                                   "border-style: inset;\n"
                                   "background: qradialgradient(\n"
                                   "cx: 0.4, cy: -0.1, fx: 0.4, fy: -0.1,\n"
                                   "radius: 1.35, stop: 0 #fff, stop: 1 #90D5FF\n"
                                   ");\n"
                                   "}\n"
                                   "QPushButton:disabled {\n"
                                   "border-style: outset;\n"
                                   "background: qradialgradient(\n"
                                   "cx: 0.4, cy: -0.1, fx: 0.4, fy: -0.1,\n"
                                   "radius: 1.35, stop: 0 #fff, stop: 1 #ddd\n"
                                   ");\n"
                                   "}\n"
                                   "")
        self.contBut.setCheckable(True)
        self.contBut.setAutoExclusive(True)
        self.contBut.setObjectName("contBut")
        self.horizontalLayout.addWidget(self.contBut)
        self.lineBut = QtWidgets.QPushButton(self)
        font = QtGui.QFont()
        font.setFamily("Figtree Light")
        font.setPointSize(11)
        self.lineBut.setFont(font)
        self.lineBut.setStyleSheet("    QPushButton{\n"
                                   "        border: 2px  solid  rgb(0, 0, 0);\n"
                                   "        background: rgb(255, 255, 255);\n"
                                   "        border-style: outset;\n"
                                   "        border-width: 1px 1px 1px 0px;\n"
                                   "        border-radius: 0px;\n"
                                   "        color: black;\n"
                                   "        padding: 5px 5px 5px 5px;   \n"
                                   "    }\n"
                                   "QPushButton:checked {\n"
                                   "border-style: inset;\n"
                                   "background: qradialgradient(\n"
                                   "cx: 0.4, cy: -0.1, fx: 0.4, fy: -0.1,\n"
                                   "radius: 1.35, stop: 0 #fff, stop: 1 #90D5FF\n"
                                   ");\n"
                                   "}\n"
                                   "QPushButton:disabled {\n"
                                   "border-style: outset;\n"
                                   "background: qradialgradient(\n"
                                   "cx: 0.4, cy: -0.1, fx: 0.4, fy: -0.1,\n"
                                   "radius: 1.35, stop: 0 #fff, stop: 1 #ddd\n"
                                   ");\n"
                                   "}\n"
                                   "")
        self.lineBut.setCheckable(True)
        self.lineBut.setAutoExclusive(True)
        self.lineBut.setObjectName("lineBut")
        self.horizontalLayout.addWidget(self.lineBut)
        spacerItem = QtWidgets.QSpacerItem(
            40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.mainVLayout.addLayout(self.horizontalLayout)
        self.tempLayout = QtWidgets.QVBoxLayout()
        self.tempLayout.setObjectName("tempLayout")
        spacerItem1 = QtWidgets.QSpacerItem(
            20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.tempLayout.addItem(spacerItem1)
        self.mainVLayout.addLayout(self.tempLayout)

        self.textBut.setText("Text Output")
        self.contBut.setText("Contour Graph")
        self.lineBut.setText("Line Cut Graph")


class resultsUiSum(QWidget):
    def __init__(self, parent):
        super().__init__(parent)
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setSpacing(4)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setSizeConstraint(QtWidgets.QLayout.SetNoConstraint)
        self.gridLayout.setContentsMargins(0, 0, -1, -1)
        self.gridLayout.setHorizontalSpacing(4)
        self.gridLayout.setVerticalSpacing(5)
        self.gridLayout.setObjectName("gridLayout")
        self.incStrainsIn = QtWidgets.QCheckBox(self)
        sizePolicy = QtWidgets.QSizePolicy(
            QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(
            self.incStrainsIn.sizePolicy().hasHeightForWidth())
        self.incStrainsIn.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Figtree Light")
        font.setPointSize(11)
        self.incStrainsIn.setFont(font)
        self.incStrainsIn.setText("")
        self.incStrainsIn.setObjectName("incStrainsIn")
        self.gridLayout.addWidget(
            self.incStrainsIn, 2, 3, 1, 1, QtCore.Qt.AlignLeft)
        self.incDispIn = QtWidgets.QCheckBox(self)
        sizePolicy = QtWidgets.QSizePolicy(
            QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(
            self.incDispIn.sizePolicy().hasHeightForWidth())
        self.incDispIn.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Figtree Light")
        font.setPointSize(11)
        self.incDispIn.setFont(font)
        self.incDispIn.setText("")
        self.incDispIn.setObjectName("incDispIn")
        self.gridLayout.addWidget(
            self.incDispIn, 2, 1, 1, 1, QtCore.Qt.AlignLeft)
        self.incDispLab = QtWidgets.QLabel(self)
        sizePolicy = QtWidgets.QSizePolicy(
            QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(
            self.incDispLab.sizePolicy().hasHeightForWidth())
        self.incDispLab.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Figtree Light")
        font.setPointSize(11)
        self.incDispLab.setFont(font)
        self.incDispLab.setObjectName("incDispLab")
        self.gridLayout.addWidget(
            self.incDispLab, 2, 0, 1, 1, QtCore.Qt.AlignLeft)
        self.imgPairLab = QtWidgets.QLabel(self)
        sizePolicy = QtWidgets.QSizePolicy(
            QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(
            self.imgPairLab.sizePolicy().hasHeightForWidth())
        self.imgPairLab.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Figtree Light")
        font.setPointSize(11)
        self.imgPairLab.setFont(font)
        self.imgPairLab.setObjectName("imgPairLab")
        self.gridLayout.addWidget(
            self.imgPairLab, 0, 0, 1, 1, QtCore.Qt.AlignLeft)
        self.incStrainsLab = QtWidgets.QLabel(self)
        sizePolicy = QtWidgets.QSizePolicy(
            QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(
            self.incStrainsLab.sizePolicy().hasHeightForWidth())
        self.incStrainsLab.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Figtree Light")
        font.setPointSize(11)
        self.incStrainsLab.setFont(font)
        self.incStrainsLab.setObjectName("incStrainsLab")
        self.gridLayout.addWidget(
            self.incStrainsLab, 2, 2, 1, 1, QtCore.Qt.AlignLeft)
        self.imgPairIn = QtWidgets.QComboBox(self)
        sizePolicy = QtWidgets.QSizePolicy(
            QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(
            self.imgPairIn.sizePolicy().hasHeightForWidth())
        self.imgPairIn.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Figtree Light")
        font.setPointSize(11)
        self.imgPairIn.setFont(font)
        self.imgPairIn.setObjectName("imgPairIn")
        self.gridLayout.addWidget(self.imgPairIn, 0, 1, 1, 1)
        self.removeNanLab = QtWidgets.QLabel(self)
        sizePolicy = QtWidgets.QSizePolicy(
            QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(
            self.removeNanLab.sizePolicy().hasHeightForWidth())
        self.removeNanLab.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Figtree Light")
        font.setPointSize(11)
        self.removeNanLab.setFont(font)
        self.removeNanLab.setObjectName("removeNanLab")
        self.gridLayout.addWidget(self.removeNanLab, 0, 2, 1, 1)
        self.removeNanIn = QtWidgets.QCheckBox(self)
        sizePolicy = QtWidgets.QSizePolicy(
            QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(
            self.removeNanIn.sizePolicy().hasHeightForWidth())
        self.removeNanIn.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Figtree Light")
        font.setPointSize(11)
        self.removeNanIn.setFont(font)
        self.removeNanIn.setText("")
        self.removeNanIn.setObjectName("removeNanIn")
        self.gridLayout.addWidget(self.removeNanIn, 0, 3, 1, 1)
        self.smoothOrderIn = QtWidgets.QLineEdit(self)
        sizePolicy = QtWidgets.QSizePolicy(
            QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(
            self.smoothOrderIn.sizePolicy().hasHeightForWidth())
        self.smoothOrderIn.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Figtree Light")
        font.setPointSize(11)
        self.smoothOrderIn.setFont(font)
        self.smoothOrderIn.setObjectName("smoothOrderIn")
        self.gridLayout.addWidget(self.smoothOrderIn, 1, 3, 1, 1)
        self.smoothOrderLab = QtWidgets.QLabel(self)
        sizePolicy = QtWidgets.QSizePolicy(
            QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(
            self.smoothOrderLab.sizePolicy().hasHeightForWidth())
        self.smoothOrderLab.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Figtree Light")
        font.setPointSize(11)
        self.smoothOrderLab.setFont(font)
        self.smoothOrderLab.setObjectName("smoothOrderLab")
        self.gridLayout.addWidget(self.smoothOrderLab, 1, 2, 1, 1)
        self.smoothWindowLab = QtWidgets.QLabel(self)
        sizePolicy = QtWidgets.QSizePolicy(
            QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(
            self.smoothWindowLab.sizePolicy().hasHeightForWidth())
        self.smoothWindowLab.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Figtree Light")
        font.setPointSize(11)
        self.smoothWindowLab.setFont(font)
        self.smoothWindowLab.setObjectName("smoothWindowLab")
        self.gridLayout.addWidget(self.smoothWindowLab, 1, 0, 1, 1)
        self.smoothWindowIn = QtWidgets.QLineEdit(self)
        sizePolicy = QtWidgets.QSizePolicy(
            QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(
            self.smoothWindowIn.sizePolicy().hasHeightForWidth())
        self.smoothWindowIn.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Figtree Light")
        font.setPointSize(11)
        self.smoothWindowIn.setFont(font)
        self.smoothWindowIn.setText("")
        self.smoothWindowIn.setObjectName("smoothWindowIn")
        self.gridLayout.addWidget(self.smoothWindowIn, 1, 1, 1, 1)
        self.verticalLayout_2.addLayout(self.gridLayout)
        self.writeDataBut = QtWidgets.QPushButton(self)
        sizePolicy = QtWidgets.QSizePolicy(
            QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(
            self.writeDataBut.sizePolicy().hasHeightForWidth())
        self.writeDataBut.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Figtree Light")
        font.setPointSize(11)
        self.writeDataBut.setFont(font)
        self.writeDataBut.setObjectName("writeDataBut")
        self.verticalLayout_2.addWidget(
            self.writeDataBut, 0, QtCore.Qt.AlignHCenter)
        spacerItem = QtWidgets.QSpacerItem(
            20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_2.addItem(spacerItem)

        self.imgPairLab.setText("Image Pair:")
        self.smoothWindowLab.setText("Smoothing Window:")
        self.smoothOrderLab.setText("Smoothing Order:")
        self.removeNanLab.setText("Remove NAN\'s:")
        self.incDispLab.setText("Include Displacements:")
        self.incStrainsLab.setText("Include Strains:")
        self.writeDataBut.setText("Write Data")


class resultsUiCon(QWidget):
    def __init__(self, parent):
        super().__init__(parent)
        self.gridLayout = QtWidgets.QGridLayout(self)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setHorizontalSpacing(5)
        self.gridLayout.setVerticalSpacing(4)
        self.gridLayout.setObjectName("gridLayout")
        self.imgPairLab = QtWidgets.QLabel(self)
        sizePolicy = QtWidgets.QSizePolicy(
            QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(
            self.imgPairLab.sizePolicy().hasHeightForWidth())
        self.imgPairLab.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Figtree Light")
        font.setPointSize(11)
        self.imgPairLab.setFont(font)
        self.imgPairLab.setObjectName("imgPairLab")
        self.gridLayout.addWidget(self.imgPairLab, 0, 0, 1, 1)
        self.imgPairIn = QtWidgets.QComboBox(self)
        sizePolicy = QtWidgets.QSizePolicy(
            QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(
            self.imgPairIn.sizePolicy().hasHeightForWidth())
        self.imgPairIn.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Figtree Light")
        font.setPointSize(11)
        self.imgPairIn.setFont(font)
        self.imgPairIn.setObjectName("imgPairIn")
        self.gridLayout.addWidget(self.imgPairIn, 0, 1, 1, 1)
        self.compLab = QtWidgets.QLabel(self)
        sizePolicy = QtWidgets.QSizePolicy(
            QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(
            self.compLab.sizePolicy().hasHeightForWidth())
        self.compLab.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Figtree Light")
        font.setPointSize(11)
        self.compLab.setFont(font)
        self.compLab.setObjectName("compLab")
        self.gridLayout.addWidget(self.compLab, 0, 2, 1, 1)
        self.compIn = QtWidgets.QComboBox(self)
        sizePolicy = QtWidgets.QSizePolicy(
            QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(
            self.compIn.sizePolicy().hasHeightForWidth())
        self.compIn.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Figtree Light")
        font.setPointSize(11)
        self.compIn.setFont(font)
        self.compIn.setObjectName("compIn")
        self.gridLayout.addWidget(self.compIn, 0, 3, 1, 1)
        self.smoothWinLab = QtWidgets.QLabel(self)
        sizePolicy = QtWidgets.QSizePolicy(
            QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(
            self.smoothWinLab.sizePolicy().hasHeightForWidth())
        self.smoothWinLab.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Figtree Light")
        font.setPointSize(11)
        self.smoothWinLab.setFont(font)
        self.smoothWinLab.setObjectName("smoothWinLab")
        self.gridLayout.addWidget(self.smoothWinLab, 1, 0, 1, 1)
        self.smoothWinIn = QtWidgets.QLineEdit(self)
        sizePolicy = QtWidgets.QSizePolicy(
            QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(
            self.smoothWinIn.sizePolicy().hasHeightForWidth())
        self.smoothWinIn.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Figtree Light")
        font.setPointSize(11)
        self.smoothWinIn.setFont(font)
        self.smoothWinIn.setObjectName("smoothWinIn")
        self.gridLayout.addWidget(self.smoothWinIn, 1, 1, 1, 1)
        self.smoothOrderLab = QtWidgets.QLabel(self)
        sizePolicy = QtWidgets.QSizePolicy(
            QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(
            self.smoothOrderLab.sizePolicy().hasHeightForWidth())
        self.smoothOrderLab.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Figtree Light")
        font.setPointSize(11)
        self.smoothOrderLab.setFont(font)
        self.smoothOrderLab.setObjectName("smoothOrderLab")
        self.gridLayout.addWidget(self.smoothOrderLab, 1, 2, 1, 1)
        self.maxValLab = QtWidgets.QLabel(self)
        sizePolicy = QtWidgets.QSizePolicy(
            QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(
            self.maxValLab.sizePolicy().hasHeightForWidth())
        self.maxValLab.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Figtree Light")
        font.setPointSize(11)
        self.maxValLab.setFont(font)
        self.maxValLab.setObjectName("maxValLab")
        self.gridLayout.addWidget(self.maxValLab, 2, 0, 1, 1)
        self.maxValIn = QtWidgets.QLineEdit(self)
        sizePolicy = QtWidgets.QSizePolicy(
            QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(
            self.maxValIn.sizePolicy().hasHeightForWidth())
        self.maxValIn.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Figtree Light")
        font.setPointSize(11)
        self.maxValIn.setFont(font)
        self.maxValIn.setObjectName("maxValIn")
        self.gridLayout.addWidget(self.maxValIn, 2, 1, 1, 1)
        self.minValLab = QtWidgets.QLabel(self)
        sizePolicy = QtWidgets.QSizePolicy(
            QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(
            self.minValLab.sizePolicy().hasHeightForWidth())
        self.minValLab.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Figtree Light")
        font.setPointSize(11)
        self.minValLab.setFont(font)
        self.minValLab.setObjectName("minValLab")
        self.gridLayout.addWidget(self.minValLab, 2, 2, 1, 1)
        self.minValIn = QtWidgets.QLineEdit(self)
        sizePolicy = QtWidgets.QSizePolicy(
            QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(
            self.minValIn.sizePolicy().hasHeightForWidth())
        self.minValIn.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Figtree Light")
        font.setPointSize(11)
        self.minValIn.setFont(font)
        self.minValIn.setObjectName("minValIn")
        self.gridLayout.addWidget(self.minValIn, 2, 3, 1, 1)
        self.alphaLab = QtWidgets.QLabel(self)
        sizePolicy = QtWidgets.QSizePolicy(
            QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(
            self.alphaLab.sizePolicy().hasHeightForWidth())
        self.alphaLab.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Figtree Light")
        font.setPointSize(11)
        self.alphaLab.setFont(font)
        self.alphaLab.setObjectName("alphaLab")
        self.gridLayout.addWidget(self.alphaLab, 3, 0, 1, 1)
        self.alphaIn = QtWidgets.QLineEdit(self)
        sizePolicy = QtWidgets.QSizePolicy(
            QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(
            self.alphaIn.sizePolicy().hasHeightForWidth())
        self.alphaIn.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Figtree Light")
        font.setPointSize(11)
        self.alphaIn.setFont(font)
        self.alphaIn.setObjectName("alphaIn")
        self.gridLayout.addWidget(self.alphaIn, 3, 1, 1, 1)
        self.smoothOrderIn = QtWidgets.QLineEdit(self)
        sizePolicy = QtWidgets.QSizePolicy(
            QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(
            self.smoothOrderIn.sizePolicy().hasHeightForWidth())
        self.smoothOrderIn.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Figtree Light")
        font.setPointSize(11)
        self.smoothOrderIn.setFont(font)
        self.smoothOrderIn.setObjectName("smoothOrderIn")
        self.gridLayout.addWidget(self.smoothOrderIn, 1, 3, 1, 1)

        self.imgPairLab.setText("Image Pair:")
        self.compLab.setText("Component:")
        self.alphaLab.setText("Alpha:")
        self.smoothWinLab.setText("Smoothing Window:")
        self.smoothOrderLab.setText("Smoothing Order:")
        self.maxValLab.setText("Max Value:")
        self.minValLab.setText("Min Value:")


class resultsUiCut(QWidget):
    def __init__(self, parent):
        super().__init__(parent)
        self.gridLayout = QtWidgets.QGridLayout(self)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setHorizontalSpacing(5)
        self.gridLayout.setVerticalSpacing(4)
        self.gridLayout.setObjectName("gridLayout")
        self.cutValLab = QtWidgets.QLabel(self)
        sizePolicy = QtWidgets.QSizePolicy(
            QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(
            self.cutValLab.sizePolicy().hasHeightForWidth())
        self.cutValLab.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Figtree Light")
        font.setPointSize(11)
        self.cutValLab.setFont(font)
        self.cutValLab.setObjectName("cutValLab")
        self.gridLayout.addWidget(self.cutValLab, 1, 2, 1, 1)
        self.imgPairLab = QtWidgets.QLabel(self)
        sizePolicy = QtWidgets.QSizePolicy(
            QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(
            self.imgPairLab.sizePolicy().hasHeightForWidth())
        self.imgPairLab.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Figtree Light")
        font.setPointSize(11)
        self.imgPairLab.setFont(font)
        self.imgPairLab.setObjectName("imgPairLab")
        self.gridLayout.addWidget(self.imgPairLab, 0, 0, 1, 1)
        self.imgPairIn = QtWidgets.QComboBox(self)
        sizePolicy = QtWidgets.QSizePolicy(
            QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(
            self.imgPairIn.sizePolicy().hasHeightForWidth())
        self.imgPairIn.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Figtree Light")
        font.setPointSize(11)
        self.imgPairIn.setFont(font)
        self.imgPairIn.setObjectName("imgPairIn")
        self.gridLayout.addWidget(self.imgPairIn, 0, 1, 1, 1)
        self.compLab = QtWidgets.QLabel(self)
        sizePolicy = QtWidgets.QSizePolicy(
            QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(
            self.compLab.sizePolicy().hasHeightForWidth())
        self.compLab.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Figtree Light")
        font.setPointSize(11)
        self.compLab.setFont(font)
        self.compLab.setObjectName("compLab")
        self.gridLayout.addWidget(self.compLab, 0, 2, 1, 1)
        self.compIn = QtWidgets.QComboBox(self)
        sizePolicy = QtWidgets.QSizePolicy(
            QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(
            self.compIn.sizePolicy().hasHeightForWidth())
        self.compIn.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Figtree Light")
        font.setPointSize(11)
        self.compIn.setFont(font)
        self.compIn.setObjectName("compIn")
        self.gridLayout.addWidget(self.compIn, 0, 3, 1, 1)
        self.cutValIn = QtWidgets.QLineEdit(self)
        sizePolicy = QtWidgets.QSizePolicy(
            QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(
            self.cutValIn.sizePolicy().hasHeightForWidth())
        self.cutValIn.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Figtree Light")
        font.setPointSize(11)
        self.cutValIn.setFont(font)
        self.cutValIn.setObjectName("cutValIn")
        self.gridLayout.addWidget(self.cutValIn, 1, 3, 1, 1)
        self.cutCompLab = QtWidgets.QLabel(self)
        sizePolicy = QtWidgets.QSizePolicy(
            QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(
            self.cutCompLab.sizePolicy().hasHeightForWidth())
        self.cutCompLab.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Figtree Light")
        font.setPointSize(11)
        self.cutCompLab.setFont(font)
        self.cutCompLab.setObjectName("cutCompLab")
        self.gridLayout.addWidget(self.cutCompLab, 1, 0, 1, 1)
        self.cutCompIn = QtWidgets.QComboBox(self)
        sizePolicy = QtWidgets.QSizePolicy(
            QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(
            self.cutCompIn.sizePolicy().hasHeightForWidth())
        self.cutCompIn.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Figtree Light")
        font.setPointSize(11)
        self.cutCompIn.setFont(font)
        self.cutCompIn.setObjectName("cutCompIn")
        self.gridLayout.addWidget(self.cutCompIn, 1, 1, 1, 1)
        self.smoothWinLab = QtWidgets.QLabel(self)
        sizePolicy = QtWidgets.QSizePolicy(
            QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(
            self.smoothWinLab.sizePolicy().hasHeightForWidth())
        self.smoothWinLab.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Figtree Light")
        font.setPointSize(11)
        self.smoothWinLab.setFont(font)
        self.smoothWinLab.setObjectName("smoothWinLab")
        self.gridLayout.addWidget(self.smoothWinLab, 2, 0, 1, 1)
        self.smoothWinIn = QtWidgets.QLineEdit(self)
        sizePolicy = QtWidgets.QSizePolicy(
            QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(
            self.smoothWinIn.sizePolicy().hasHeightForWidth())
        self.smoothWinIn.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Figtree Light")
        font.setPointSize(11)
        self.smoothWinIn.setFont(font)
        self.smoothWinIn.setObjectName("smoothWinIn")
        self.gridLayout.addWidget(self.smoothWinIn, 2, 1, 1, 1)
        self.smoothOrderLab = QtWidgets.QLabel(self)
        sizePolicy = QtWidgets.QSizePolicy(
            QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(
            self.smoothOrderLab.sizePolicy().hasHeightForWidth())
        self.smoothOrderLab.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Figtree Light")
        font.setPointSize(11)
        self.smoothOrderLab.setFont(font)
        self.smoothOrderLab.setObjectName("smoothOrderLab")
        self.gridLayout.addWidget(self.smoothOrderLab, 2, 2, 1, 1)
        self.smoothOrderIn = QtWidgets.QLineEdit(self)
        sizePolicy = QtWidgets.QSizePolicy(
            QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(
            self.smoothOrderIn.sizePolicy().hasHeightForWidth())
        self.smoothOrderIn.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Figtree Light")
        font.setPointSize(11)
        self.smoothOrderIn.setFont(font)
        self.smoothOrderIn.setObjectName("smoothOrderIn")
        self.gridLayout.addWidget(self.smoothOrderIn, 2, 3, 1, 1)
        self.interpLab = QtWidgets.QLabel(self)
        sizePolicy = QtWidgets.QSizePolicy(
            QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(
            self.interpLab.sizePolicy().hasHeightForWidth())
        self.interpLab.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Figtree Light")
        font.setPointSize(11)
        self.interpLab.setFont(font)
        self.interpLab.setObjectName("interpLab")
        self.gridLayout.addWidget(self.interpLab, 4, 0, 1, 1)
        self.interpIn = QtWidgets.QCheckBox(self)
        sizePolicy = QtWidgets.QSizePolicy(
            QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(
            self.interpIn.sizePolicy().hasHeightForWidth())
        self.interpIn.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Figtree Light")
        font.setPointSize(11)
        self.interpIn.setFont(font)
        self.interpIn.setText("")
        self.interpIn.setObjectName("interpIn")
        self.gridLayout.addWidget(self.interpIn, 4, 1, 1, 1)
        self.gridLinesLab = QtWidgets.QLabel(self)
        sizePolicy = QtWidgets.QSizePolicy(
            QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(
            self.gridLinesLab.sizePolicy().hasHeightForWidth())
        self.gridLinesLab.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Figtree Light")
        font.setPointSize(11)
        self.gridLinesLab.setFont(font)
        self.gridLinesLab.setObjectName("gridLinesLab")
        self.gridLayout.addWidget(self.gridLinesLab, 4, 2, 1, 1)
        self.gridLinesIn = QtWidgets.QCheckBox(self)
        sizePolicy = QtWidgets.QSizePolicy(
            QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(
            self.gridLinesIn.sizePolicy().hasHeightForWidth())
        self.gridLinesIn.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Figtree Light")
        font.setPointSize(11)
        self.gridLinesIn.setFont(font)
        self.gridLinesIn.setText("")
        self.gridLinesIn.setObjectName("gridLinesIn")
        self.gridLayout.addWidget(self.gridLinesIn, 4, 3, 1, 1)

        self.imgPairLab.setText("Image Pair:")
        self.compLab.setText("Display Component:")
        self.cutValLab.setText("Cut Values:")
        self.interpLab.setText("Interpolate:")
        self.cutCompLab.setText("Cut Component:")
        self.smoothWinLab.setText("Smoothing Window:")
        self.smoothOrderLab.setText("Smoothing Order:")
        self.gridLinesLab.setText("Grid Lines:")
