
# This file was generated by 'versioneer.py' (0.19) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2025-09-03T20:33:44+0200",
 "dirty": false,
 "error": null,
 "full-revisionid": "b4a2452942419d0c9c757fdb46bb85f7a404347d",
 "version": "2.69.2b0"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
