from minjiang_client.com.log import add_cali_execution_log as add_cali_execution_log
from minjiang_client.com.minio import MinIOAPI as MinIOAPI
from minjiang_client.com.oss import add_resource as add_resource, get_resource_info as get_resource_info
from minjiang_client.com.task import save_cali_result as save_cali_result
from minjiang_client.group.cloud_group import CloudGroup as CloudGroup

def upload_auto_cali_json(json_path: str) -> int: ...
def load_json_file_data(resource_id: int) -> dict: ...
def get_session_entities(device_group_name: str, space_id: int): ...
def upload_fitting_img(exp_id: int, img_path: str): ...
