"""Core GDSFactory+ utilities."""

from __future__ import annotations

import lazy_loader

__getattr__, __dir__, __all__ = lazy_loader.attach_stub(__name__, __file__)

__all__ = [
    "F",
    "FrozenPdk",
    "activate_pdk_by_name",
    "add_components",
    "add_factories",
    "add_models",
    "build_by_names",
    "clear_cells_from_cache",
    "create_callgraph",
    "deduplicate",
    "default_lib_paths",
    "extract_function_arguments",
    "find_models",
    "find_partial_definition",
    "find_source_path",
    "generate_multipolygon",
    "generate_svg",
    "get_all_factories",
    "get_all_factory_names",
    "get_all_models",
    "get_base_pdk",
    "get_base_schema",
    "get_cells_from_regex",
    "get_components_by_factories",
    "get_factories_by_components",
    "get_factories_by_idxs",
    "get_factories_by_name",
    "get_factory_sources_by_name",
    "get_model_sources_by_name",
    "get_models_by_name",
    "get_netlist_schema",
    "get_pdk",
    "get_ports",
    "get_runtime_factories_dependency_graph",
    "get_runtime_factory_dependencies",
    "get_static_factory_dependencies",
    "get_static_records",
    "get_static_records_by_path",
    "get_svg",
    "get_tags",
    "get_ws_port",
    "import_modules",
    "import_path",
    "import_picyml",
    "import_reload",
    "lazy_import",
    "lazy_setattr",
    "merge_rdb_strings",
    "plot_callgraph",
    "register_cells",
    "register_models",
    "remove_components",
    "remove_components_by_factories",
    "remove_factories",
    "remove_models",
    "reset_timestamps",
    "resolve_modname",
    "send_message",
    "set_all_factories_has_model",
    "set_factories_has_model_by_names",
    "set_factories_status_by_names",
    "sync_from_kcl",
    "try_func",
    "unlazy",
    "validate_access",
]
