import os,sys,typer
current_file_path=os.path.abspath(__file__)
parent_directory=os.path.dirname(current_file_path)
sys.path.insert(0,parent_directory)
app=typer.Typer()
@app.command()
def sparta_92ad63b449(port=None,background=True):spartaqube_cli.list()
@app.command()
def sparta_1fca39b9a9():spartaqube_cli.list()
@app.command()
def sparta_dff6929791():spartaqube_cli.sparta_dff6929791()
@app.command()
def sparta_4d4d41a39f():print('Hello world!')
if __name__=='__main__':app()