from minjiang_client.com.request import request as request

def create_plugin(plugin_name: str, description: str, must_be_installed: bool = False, auto_upgrade: bool = False): ...
def list_plugins(page: int = 1, per_page: int = 10): ...
def list_plugin_versions(plugin_id: int, page: int = 1, per_page: int = 10): ...
def upload_plugin_version(plugin_id: int, version_code_level1: int, version_code_level2: int, version_code_level3: int, version_code_postfix: str, full_version_code: str, update_description: str, hook: str, resource_id: int): ...
def disable_plugin(plugin_id: int, plugin_version_id: int = None, plugin_status: bool = False): ...
def get_plugin_detail(plugin_id: int): ...
def get_plugin_version_detail(plugin_version_id: int): ...
def download_plugin_version(plugin_version_id: int): ...
