# coding: utf-8

"""
    Kalshi Trading API

    Complete API for the Kalshi trading platform including all handlers for SDK generation

    The version of the OpenAPI document: 2.0.0
    Contact: support@kalshi.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from kalshi_api_v2_external.models.create_order_group_response import CreateOrderGroupResponse

class TestCreateOrderGroupResponse(unittest.TestCase):
    """CreateOrderGroupResponse unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> CreateOrderGroupResponse:
        """Test CreateOrderGroupResponse
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `CreateOrderGroupResponse`
        """
        model = CreateOrderGroupResponse()
        if include_optional:
            return CreateOrderGroupResponse(
                order_group = kalshi_api_v2_external.models.order_group.OrderGroup(
                    order_group_id = '', 
                    name = '', 
                    status = '', 
                    created_time = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), )
            )
        else:
            return CreateOrderGroupResponse(
        )
        """

    def testCreateOrderGroupResponse(self):
        """Test CreateOrderGroupResponse"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
