# coding: utf-8

"""
    Kalshi Trading API

    Complete API for the Kalshi trading platform including all handlers for SDK generation

    The version of the OpenAPI document: 2.0.0
    Contact: support@kalshi.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from kalshi_api_v2_external.models.get_settlements_response import GetSettlementsResponse

class TestGetSettlementsResponse(unittest.TestCase):
    """GetSettlementsResponse unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> GetSettlementsResponse:
        """Test GetSettlementsResponse
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `GetSettlementsResponse`
        """
        model = GetSettlementsResponse()
        if include_optional:
            return GetSettlementsResponse(
                settlements = [
                    kalshi_api_v2_external.models.settlement.Settlement(
                        ticker = '', 
                        result = 'yes', 
                        yes_count = 56, 
                        no_count = 56, 
                        revenue = 56, 
                        settled_time = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), )
                    ],
                cursor = ''
            )
        else:
            return GetSettlementsResponse(
        )
        """

    def testGetSettlementsResponse(self):
        """Test GetSettlementsResponse"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
