# coding: utf-8

"""
    Kalshi Trading API

    Complete API for the Kalshi trading platform including all handlers for SDK generation

    The version of the OpenAPI document: 2.0.0
    Contact: support@kalshi.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from kalshi_api_v2_external.models.batch_cancel_orders_response_responses_inner import BatchCancelOrdersResponseResponsesInner

class TestBatchCancelOrdersResponseResponsesInner(unittest.TestCase):
    """BatchCancelOrdersResponseResponsesInner unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> BatchCancelOrdersResponseResponsesInner:
        """Test BatchCancelOrdersResponseResponsesInner
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `BatchCancelOrdersResponseResponsesInner`
        """
        model = BatchCancelOrdersResponseResponsesInner()
        if include_optional:
            return BatchCancelOrdersResponseResponsesInner(
                order_id = '',
                reduced_by = 56,
                error = kalshi_api_v2_external.models.error_response.ErrorResponse(
                    error = kalshi_api_v2_external.models.error_response_error.ErrorResponse_error(
                        code = '', 
                        message = '', 
                        details = kalshi_api_v2_external.models.details.details(), ), )
            )
        else:
            return BatchCancelOrdersResponseResponsesInner(
        )
        """

    def testBatchCancelOrdersResponseResponsesInner(self):
        """Test BatchCancelOrdersResponseResponsesInner"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
