# coding: utf-8

"""
    Kalshi Trading API

    Complete API for the Kalshi trading platform including all handlers for SDK generation

    The version of the OpenAPI document: 2.0.0
    Contact: support@kalshi.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from kalshi_api_v2_external.api.milestones_api import MilestonesApi


class TestMilestonesApi(unittest.TestCase):
    """MilestonesApi unit test stubs"""

    def setUp(self) -> None:
        self.api = MilestonesApi()

    def tearDown(self) -> None:
        pass

    def test_get_milestone(self) -> None:
        """Test case for get_milestone

        Get Milestone
        """
        pass

    def test_get_milestones(self) -> None:
        """Test case for get_milestones

        Get Milestones
        """
        pass


if __name__ == '__main__':
    unittest.main()
