from typing import Literal

SAMPLE_WEIGHT: str
EXAMPLE_ID: str
EPOCH: str
FOREIGN_TABLE_ID: str
IMAGE: str
LABEL: str
HEIGHT: str
WIDTH: str
IMAGE_HEIGHT: Literal['image_height']
IMAGE_WIDTH: Literal['image_width']
BOUNDING_BOXES: str
PREDICTED_BOUNDING_BOXES: str
BOUNDING_BOX_LIST: str
TRUE_POSITIVE: str
FALSE_POSITIVE: str
FALSE_NEGATIVE: str
IOU: str
CONFIDENCE: str
SEGMENTATION: str
X0: str
Y0: str
X1: str
Y1: str
IS_CROWD: str
RUN_STATUS: str
RUN_STATUS_COMPLETED: float
RUN_STATUS_EMPTY: float
RUN_STATUS_RUNNING: float
RUN_STATUS_COLLECTING: float
RUN_STATUS_POST_PROCESSING: float
RUN_STATUS_PAUSED: float
RUN_STATUS_CANCELLED: float
SHOULD_DELETE: str
EMBEDDING_COL_NAME: str
PREDICTED_MASK: str
PIXELS: str
SIZE_X: str
SIZE_Y: str
SIZE_Z: str
VOXELS: str
GT_IOUS: Literal['gt_ious']
SEGMENTATION_DATA: Literal['segmentation_data']
PIXEL_COUNTS: Literal['pixel_counts']
MIN_XS: Literal['min_xs']
MIN_YS: Literal['min_ys']
MAX_XS: Literal['max_xs']
MAX_YS: Literal['max_ys']
SEGMENTATIONS: str
PREDICTED_SEGMENTATIONS: str
INSTANCE_PROPERTIES: Literal['instance_properties']
MASKS: Literal['masks']
POLYGONS: Literal['polygons']
ISLAND_COUNTS: Literal['island_counts']
CIRCUMFERENCES: Literal['circumferences']
RLES: Literal['rles']
