"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from enode.types import BaseModel
from enode.utils import FieldMetadata, PathParamMetadata
import pydantic
from typing_extensions import Annotated, TypedDict


class GetChargerRequestTypedDict(TypedDict):
    charger_id: str


class GetChargerRequest(BaseModel):
    charger_id: Annotated[
        str,
        pydantic.Field(alias="chargerId"),
        FieldMetadata(path=PathParamMetadata(style="simple", explode=False)),
    ]
