from enum import Enum


class LifeType(Enum):
    # PROCESS
    DATA_PROCESSING = "DATA_PROCESSING"
    DATA_PROCESSED = "DATA_PROCESSED"
    DATA_PROCESS_FAILED = "DATA_PROCESS_FAILED"

    # CLEAN
    DATA_CLEANING = "DATA_CLEANING"
    DATA_CLEANED = "DATA_CLEANED"
    DATA_CLEAN_FAILED = "DATA_CLEAN_FAILED"

    # LABEL
    DATA_LABELLING = "DATA_LABELLING"
    DATA_LABELLED = "DATA_LABELLED"
    DATA_LABEL_FAILED = "DATA_LABEL_FAILED"

    # CRAWL
    DATA_CRAWLING = "DATA_CRAWLING"
    DATA_CRAWLED = "DATA_CRAWLED"
    DATA_CRAWL_FAILED = "DATA_CRAWL_FAILED"
