"""
@generated by mypy-protobuf.  Do not edit manually!
isort:skip_file
"""

import builtins
import collections.abc
import google.protobuf.descriptor
import google.protobuf.internal.containers
import google.protobuf.message
import k8s.io.api.core.v1.generated_pb2
import typing

DESCRIPTOR: google.protobuf.descriptor.FileDescriptor

@typing.final
class LogRequest(google.protobuf.message.Message):
    """swagger:model"""

    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    JOB_ID_FIELD_NUMBER: builtins.int
    POD_NUMBER_FIELD_NUMBER: builtins.int
    POD_NAMESPACE_FIELD_NUMBER: builtins.int
    SINCE_TIME_FIELD_NUMBER: builtins.int
    LOG_OPTIONS_FIELD_NUMBER: builtins.int
    job_id: builtins.str
    pod_number: builtins.int
    pod_namespace: builtins.str
    since_time: builtins.str
    """allows to specify high precision time as string"""
    @property
    def log_options(self) -> k8s.io.api.core.v1.generated_pb2.PodLogOptions: ...
    def __init__(
        self,
        *,
        job_id: builtins.str = ...,
        pod_number: builtins.int = ...,
        pod_namespace: builtins.str = ...,
        since_time: builtins.str = ...,
        log_options: k8s.io.api.core.v1.generated_pb2.PodLogOptions | None = ...,
    ) -> None: ...
    def HasField(self, field_name: typing.Literal["log_options", b"log_options"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing.Literal["job_id", b"job_id", "log_options", b"log_options", "pod_namespace", b"pod_namespace", "pod_number", b"pod_number", "since_time", b"since_time"]) -> None: ...

global___LogRequest = LogRequest

@typing.final
class LogResponse(google.protobuf.message.Message):
    """swagger:model"""

    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    LOG_FIELD_NUMBER: builtins.int
    @property
    def log(self) -> google.protobuf.internal.containers.RepeatedCompositeFieldContainer[global___LogLine]: ...
    def __init__(
        self,
        *,
        log: collections.abc.Iterable[global___LogLine] | None = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing.Literal["log", b"log"]) -> None: ...

global___LogResponse = LogResponse

@typing.final
class LogLine(google.protobuf.message.Message):
    """swagger:model"""

    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    TIMESTAMP_FIELD_NUMBER: builtins.int
    LINE_FIELD_NUMBER: builtins.int
    timestamp: builtins.str
    line: builtins.str
    def __init__(
        self,
        *,
        timestamp: builtins.str = ...,
        line: builtins.str = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing.Literal["line", b"line", "timestamp", b"timestamp"]) -> None: ...

global___LogLine = LogLine

@typing.final
class CordonRequest(google.protobuf.message.Message):
    """swagger:model"""

    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    NODE_NAME_FIELD_NUMBER: builtins.int
    node_name: builtins.str
    def __init__(
        self,
        *,
        node_name: builtins.str = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing.Literal["node_name", b"node_name"]) -> None: ...

global___CordonRequest = CordonRequest
