# coding: utf-8

"""
Notehub API

The OpenAPI definition for the Notehub.io API.

The version of the OpenAPI document: 1.2.0
Contact: engineering@blues.io
Generated by OpenAPI Generator (https://openapi-generator.tech)

Do not edit the class manually.
"""  # noqa: E501


import unittest

from notehub_py.models.user_firmware_info import UserFirmwareInfo


class TestUserFirmwareInfo(unittest.TestCase):
    """UserFirmwareInfo unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> UserFirmwareInfo:
        """Test UserFirmwareInfo
        include_option is a boolean, when False only required
        params are included, when True both required and
        optional params are included"""
        # uncomment below to create an instance of `UserFirmwareInfo`
        """
        model = UserFirmwareInfo()
        if include_optional:
            return UserFirmwareInfo(
                current_firmware = notehub_py.models.current_firmware.CurrentFirmware(
                    version = '', 
                    metadata = notehub_py.models.firmware.Firmware(
                        org = '', 
                        product = '', 
                        firmware = '', 
                        version = '', 
                        target = '', 
                        ver_major = 56, 
                        ver_minor = 56, 
                        ver_patch = 56, 
                        ver_build = 56, 
                        built = '', 
                        builder = '', ), ),
                firmware_update = notehub_py.models.user_dfu_state_machine.UserDfuStateMachine(
                    status = notehub_py.models.user_dfu_state_machine_status.UserDfuStateMachineStatus(
                        phase = '', 
                        phase_description = '', 
                        date = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), ), 
                    created = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), 
                    from_version = '', 
                    metadata = notehub_py.models.upload_metadata.UploadMetadata(
                        name = '', 
                        length = 56, 
                        md5 = '', 
                        crc32 = 56, 
                        created = 56, 
                        modified = 56, 
                        source = '', 
                        contains = '', 
                        found = '', 
                        type = '', 
                        tags = '', 
                        notes = '', 
                        firmware = notehub_py.models.firmware.Firmware(
                            org = '', 
                            product = '', 
                            version = '', 
                            target = '', 
                            ver_major = 56, 
                            ver_minor = 56, 
                            ver_patch = 56, 
                            ver_build = 56, 
                            built = '', 
                            builder = '', ), ), )
            )
        else:
            return UserFirmwareInfo(
        )
        """

    def testUserFirmwareInfo(self):
        """Test UserFirmwareInfo"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)


if __name__ == "__main__":
    unittest.main()
