"""
Configuration management.

Contains all configuration settings and system prompts.
"""

from .settings import *

__all__ = [
    "LLM_MODEL", "LLM_PROVIDER", "LLM_TEMPERATURE", "LLM_REASONING_EFFORT",
    "SUMMARIZER_MODEL", "SUMMARIZER_PROVIDER", "SUMMARIZER_REASONING_EFFORT",
    "SYSTEM_TEMPLATE", "ENABLE_SUMMARIZATION",
    "BROWSER_EXECUTABLE_PATH", "USER_DATA_DIR", "DEFAULT_PERMISSIONS",
    "RECURSION_LIMIT", "MAX_ITERATIONS", "TIMEOUT",
    "ACTIVATE_HUMAN_BEHAVIOR", "HUMAN_BEHAVIOR", "HUMAN_BEHAVIOR_SEED",
    "FINGERPRINT_PROFILES", "FINGERPRINT_CUSTOMIZATION", "STEALTH_ARGS",
    "ACTUAL_VIEWPORT_WIDTH", "ACTUAL_VIEWPORT_HEIGHT",
    "GROUPCHAT_ROOM", "REDIS_HOST", "REDIS_PORT", "REDIS_DB",
    "MAX_KAGEBUNSHIN_INSTANCES",
]