# coding: utf-8

# flake8: noqa
"""
    Kalshi Trading API

    Complete API for the Kalshi trading platform including all handlers for SDK generation

    The version of the OpenAPI document: 2.0.0
    Contact: support@kalshi.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


if __import__("typing").TYPE_CHECKING:
    # import models into model package
    from kalshi_api_v2_external.models.accept_quote_request import AcceptQuoteRequest
    from kalshi_api_v2_external.models.amend_order_request import AmendOrderRequest
    from kalshi_api_v2_external.models.amend_order_response import AmendOrderResponse
    from kalshi_api_v2_external.models.announcement import Announcement
    from kalshi_api_v2_external.models.api_key import ApiKey
    from kalshi_api_v2_external.models.batch_cancel_orders_request import BatchCancelOrdersRequest
    from kalshi_api_v2_external.models.batch_cancel_orders_response import BatchCancelOrdersResponse
    from kalshi_api_v2_external.models.batch_cancel_orders_response_responses_inner import BatchCancelOrdersResponseResponsesInner
    from kalshi_api_v2_external.models.batch_create_orders_request import BatchCreateOrdersRequest
    from kalshi_api_v2_external.models.batch_create_orders_response import BatchCreateOrdersResponse
    from kalshi_api_v2_external.models.batch_create_orders_response_responses_inner import BatchCreateOrdersResponseResponsesInner
    from kalshi_api_v2_external.models.cancel_order_response import CancelOrderResponse
    from kalshi_api_v2_external.models.candlestick import Candlestick
    from kalshi_api_v2_external.models.create_api_key_request import CreateApiKeyRequest
    from kalshi_api_v2_external.models.create_api_key_response import CreateApiKeyResponse
    from kalshi_api_v2_external.models.create_order_group_request import CreateOrderGroupRequest
    from kalshi_api_v2_external.models.create_order_group_response import CreateOrderGroupResponse
    from kalshi_api_v2_external.models.create_order_request import CreateOrderRequest
    from kalshi_api_v2_external.models.create_order_response import CreateOrderResponse
    from kalshi_api_v2_external.models.create_quote_request import CreateQuoteRequest
    from kalshi_api_v2_external.models.create_quote_response import CreateQuoteResponse
    from kalshi_api_v2_external.models.create_rfq_request import CreateRFQRequest
    from kalshi_api_v2_external.models.create_rfq_response import CreateRFQResponse
    from kalshi_api_v2_external.models.daily_schedule import DailySchedule
    from kalshi_api_v2_external.models.decrease_order_request import DecreaseOrderRequest
    from kalshi_api_v2_external.models.decrease_order_response import DecreaseOrderResponse
    from kalshi_api_v2_external.models.error_response import ErrorResponse
    from kalshi_api_v2_external.models.error_response_error import ErrorResponseError
    from kalshi_api_v2_external.models.event import Event
    from kalshi_api_v2_external.models.exchange_status import ExchangeStatus
    from kalshi_api_v2_external.models.fill import Fill
    from kalshi_api_v2_external.models.generate_api_key_request import GenerateApiKeyRequest
    from kalshi_api_v2_external.models.generate_api_key_response import GenerateApiKeyResponse
    from kalshi_api_v2_external.models.get_api_keys_response import GetApiKeysResponse
    from kalshi_api_v2_external.models.get_balance_response import GetBalanceResponse
    from kalshi_api_v2_external.models.get_communications_id_response import GetCommunicationsIDResponse
    from kalshi_api_v2_external.models.get_event_metadata_response import GetEventMetadataResponse
    from kalshi_api_v2_external.models.get_event_response import GetEventResponse
    from kalshi_api_v2_external.models.get_events_response import GetEventsResponse
    from kalshi_api_v2_external.models.get_exchange_announcements_response import GetExchangeAnnouncementsResponse
    from kalshi_api_v2_external.models.get_exchange_schedule_response import GetExchangeScheduleResponse
    from kalshi_api_v2_external.models.get_exchange_schedule_response_schedule import GetExchangeScheduleResponseSchedule
    from kalshi_api_v2_external.models.get_fills_response import GetFillsResponse
    from kalshi_api_v2_external.models.get_market_candlesticks_response import GetMarketCandlesticksResponse
    from kalshi_api_v2_external.models.get_market_orderbook_response import GetMarketOrderbookResponse
    from kalshi_api_v2_external.models.get_market_orderbook_response_orderbook import GetMarketOrderbookResponseOrderbook
    from kalshi_api_v2_external.models.get_market_response import GetMarketResponse
    from kalshi_api_v2_external.models.get_markets_response import GetMarketsResponse
    from kalshi_api_v2_external.models.get_milestone_response import GetMilestoneResponse
    from kalshi_api_v2_external.models.get_milestones_response import GetMilestonesResponse
    from kalshi_api_v2_external.models.get_multivariate_event_collection_response import GetMultivariateEventCollectionResponse
    from kalshi_api_v2_external.models.get_multivariate_event_collections_response import GetMultivariateEventCollectionsResponse
    from kalshi_api_v2_external.models.get_order_groups_response import GetOrderGroupsResponse
    from kalshi_api_v2_external.models.get_order_queue_position_response import GetOrderQueuePositionResponse
    from kalshi_api_v2_external.models.get_order_response import GetOrderResponse
    from kalshi_api_v2_external.models.get_orders_response import GetOrdersResponse
    from kalshi_api_v2_external.models.get_positions_response import GetPositionsResponse
    from kalshi_api_v2_external.models.get_queue_positions_request import GetQueuePositionsRequest
    from kalshi_api_v2_external.models.get_queue_positions_response import GetQueuePositionsResponse
    from kalshi_api_v2_external.models.get_quote_response import GetQuoteResponse
    from kalshi_api_v2_external.models.get_quotes_response import GetQuotesResponse
    from kalshi_api_v2_external.models.get_rfq_response import GetRFQResponse
    from kalshi_api_v2_external.models.get_rfqs_response import GetRFQsResponse
    from kalshi_api_v2_external.models.get_series_by_ticker_response import GetSeriesByTickerResponse
    from kalshi_api_v2_external.models.get_series_response import GetSeriesResponse
    from kalshi_api_v2_external.models.get_settlements_response import GetSettlementsResponse
    from kalshi_api_v2_external.models.get_structured_target_response import GetStructuredTargetResponse
    from kalshi_api_v2_external.models.get_structured_targets_response import GetStructuredTargetsResponse
    from kalshi_api_v2_external.models.get_total_resting_order_value_response import GetTotalRestingOrderValueResponse
    from kalshi_api_v2_external.models.get_trades_response import GetTradesResponse
    from kalshi_api_v2_external.models.get_user_data_timestamp_response import GetUserDataTimestampResponse
    from kalshi_api_v2_external.models.lookup_bundle_request import LookupBundleRequest
    from kalshi_api_v2_external.models.lookup_bundle_request_bundle_inner import LookupBundleRequestBundleInner
    from kalshi_api_v2_external.models.lookup_bundle_response import LookupBundleResponse
    from kalshi_api_v2_external.models.market import Market
    from kalshi_api_v2_external.models.milestone import Milestone
    from kalshi_api_v2_external.models.multivariate_event_collection import MultivariateEventCollection
    from kalshi_api_v2_external.models.multivariate_event_collection_events_inner import MultivariateEventCollectionEventsInner
    from kalshi_api_v2_external.models.order import Order
    from kalshi_api_v2_external.models.order_group import OrderGroup
    from kalshi_api_v2_external.models.orderbook_level import OrderbookLevel
    from kalshi_api_v2_external.models.position import Position
    from kalshi_api_v2_external.models.quote import Quote
    from kalshi_api_v2_external.models.rfq import RFQ
    from kalshi_api_v2_external.models.series import Series
    from kalshi_api_v2_external.models.settlement import Settlement
    from kalshi_api_v2_external.models.structured_target import StructuredTarget
    from kalshi_api_v2_external.models.trade import Trade
    
else:
    from lazy_imports import LazyModule, as_package, load

    load(
        LazyModule(
            *as_package(__file__),
            """# import models into model package
from kalshi_api_v2_external.models.accept_quote_request import AcceptQuoteRequest
from kalshi_api_v2_external.models.amend_order_request import AmendOrderRequest
from kalshi_api_v2_external.models.amend_order_response import AmendOrderResponse
from kalshi_api_v2_external.models.announcement import Announcement
from kalshi_api_v2_external.models.api_key import ApiKey
from kalshi_api_v2_external.models.batch_cancel_orders_request import BatchCancelOrdersRequest
from kalshi_api_v2_external.models.batch_cancel_orders_response import BatchCancelOrdersResponse
from kalshi_api_v2_external.models.batch_cancel_orders_response_responses_inner import BatchCancelOrdersResponseResponsesInner
from kalshi_api_v2_external.models.batch_create_orders_request import BatchCreateOrdersRequest
from kalshi_api_v2_external.models.batch_create_orders_response import BatchCreateOrdersResponse
from kalshi_api_v2_external.models.batch_create_orders_response_responses_inner import BatchCreateOrdersResponseResponsesInner
from kalshi_api_v2_external.models.cancel_order_response import CancelOrderResponse
from kalshi_api_v2_external.models.candlestick import Candlestick
from kalshi_api_v2_external.models.create_api_key_request import CreateApiKeyRequest
from kalshi_api_v2_external.models.create_api_key_response import CreateApiKeyResponse
from kalshi_api_v2_external.models.create_order_group_request import CreateOrderGroupRequest
from kalshi_api_v2_external.models.create_order_group_response import CreateOrderGroupResponse
from kalshi_api_v2_external.models.create_order_request import CreateOrderRequest
from kalshi_api_v2_external.models.create_order_response import CreateOrderResponse
from kalshi_api_v2_external.models.create_quote_request import CreateQuoteRequest
from kalshi_api_v2_external.models.create_quote_response import CreateQuoteResponse
from kalshi_api_v2_external.models.create_rfq_request import CreateRFQRequest
from kalshi_api_v2_external.models.create_rfq_response import CreateRFQResponse
from kalshi_api_v2_external.models.daily_schedule import DailySchedule
from kalshi_api_v2_external.models.decrease_order_request import DecreaseOrderRequest
from kalshi_api_v2_external.models.decrease_order_response import DecreaseOrderResponse
from kalshi_api_v2_external.models.error_response import ErrorResponse
from kalshi_api_v2_external.models.error_response_error import ErrorResponseError
from kalshi_api_v2_external.models.event import Event
from kalshi_api_v2_external.models.exchange_status import ExchangeStatus
from kalshi_api_v2_external.models.fill import Fill
from kalshi_api_v2_external.models.generate_api_key_request import GenerateApiKeyRequest
from kalshi_api_v2_external.models.generate_api_key_response import GenerateApiKeyResponse
from kalshi_api_v2_external.models.get_api_keys_response import GetApiKeysResponse
from kalshi_api_v2_external.models.get_balance_response import GetBalanceResponse
from kalshi_api_v2_external.models.get_communications_id_response import GetCommunicationsIDResponse
from kalshi_api_v2_external.models.get_event_metadata_response import GetEventMetadataResponse
from kalshi_api_v2_external.models.get_event_response import GetEventResponse
from kalshi_api_v2_external.models.get_events_response import GetEventsResponse
from kalshi_api_v2_external.models.get_exchange_announcements_response import GetExchangeAnnouncementsResponse
from kalshi_api_v2_external.models.get_exchange_schedule_response import GetExchangeScheduleResponse
from kalshi_api_v2_external.models.get_exchange_schedule_response_schedule import GetExchangeScheduleResponseSchedule
from kalshi_api_v2_external.models.get_fills_response import GetFillsResponse
from kalshi_api_v2_external.models.get_market_candlesticks_response import GetMarketCandlesticksResponse
from kalshi_api_v2_external.models.get_market_orderbook_response import GetMarketOrderbookResponse
from kalshi_api_v2_external.models.get_market_orderbook_response_orderbook import GetMarketOrderbookResponseOrderbook
from kalshi_api_v2_external.models.get_market_response import GetMarketResponse
from kalshi_api_v2_external.models.get_markets_response import GetMarketsResponse
from kalshi_api_v2_external.models.get_milestone_response import GetMilestoneResponse
from kalshi_api_v2_external.models.get_milestones_response import GetMilestonesResponse
from kalshi_api_v2_external.models.get_multivariate_event_collection_response import GetMultivariateEventCollectionResponse
from kalshi_api_v2_external.models.get_multivariate_event_collections_response import GetMultivariateEventCollectionsResponse
from kalshi_api_v2_external.models.get_order_groups_response import GetOrderGroupsResponse
from kalshi_api_v2_external.models.get_order_queue_position_response import GetOrderQueuePositionResponse
from kalshi_api_v2_external.models.get_order_response import GetOrderResponse
from kalshi_api_v2_external.models.get_orders_response import GetOrdersResponse
from kalshi_api_v2_external.models.get_positions_response import GetPositionsResponse
from kalshi_api_v2_external.models.get_queue_positions_request import GetQueuePositionsRequest
from kalshi_api_v2_external.models.get_queue_positions_response import GetQueuePositionsResponse
from kalshi_api_v2_external.models.get_quote_response import GetQuoteResponse
from kalshi_api_v2_external.models.get_quotes_response import GetQuotesResponse
from kalshi_api_v2_external.models.get_rfq_response import GetRFQResponse
from kalshi_api_v2_external.models.get_rfqs_response import GetRFQsResponse
from kalshi_api_v2_external.models.get_series_by_ticker_response import GetSeriesByTickerResponse
from kalshi_api_v2_external.models.get_series_response import GetSeriesResponse
from kalshi_api_v2_external.models.get_settlements_response import GetSettlementsResponse
from kalshi_api_v2_external.models.get_structured_target_response import GetStructuredTargetResponse
from kalshi_api_v2_external.models.get_structured_targets_response import GetStructuredTargetsResponse
from kalshi_api_v2_external.models.get_total_resting_order_value_response import GetTotalRestingOrderValueResponse
from kalshi_api_v2_external.models.get_trades_response import GetTradesResponse
from kalshi_api_v2_external.models.get_user_data_timestamp_response import GetUserDataTimestampResponse
from kalshi_api_v2_external.models.lookup_bundle_request import LookupBundleRequest
from kalshi_api_v2_external.models.lookup_bundle_request_bundle_inner import LookupBundleRequestBundleInner
from kalshi_api_v2_external.models.lookup_bundle_response import LookupBundleResponse
from kalshi_api_v2_external.models.market import Market
from kalshi_api_v2_external.models.milestone import Milestone
from kalshi_api_v2_external.models.multivariate_event_collection import MultivariateEventCollection
from kalshi_api_v2_external.models.multivariate_event_collection_events_inner import MultivariateEventCollectionEventsInner
from kalshi_api_v2_external.models.order import Order
from kalshi_api_v2_external.models.order_group import OrderGroup
from kalshi_api_v2_external.models.orderbook_level import OrderbookLevel
from kalshi_api_v2_external.models.position import Position
from kalshi_api_v2_external.models.quote import Quote
from kalshi_api_v2_external.models.rfq import RFQ
from kalshi_api_v2_external.models.series import Series
from kalshi_api_v2_external.models.settlement import Settlement
from kalshi_api_v2_external.models.structured_target import StructuredTarget
from kalshi_api_v2_external.models.trade import Trade

""",
            name=__name__,
            doc=__doc__,
        )
    )
