COLORS = {
    "black": [0, 0, 0],
    "white": [1, 1, 1],
    "red": [1, 0, 0],
    "blue": [0, 0, 1],
    "green": [0, 1, 0],
}


DIMENSION_MULTIPLIER = 20

DASH_PARAMETERS = [DIMENSION_MULTIPLIER / 5, DIMENSION_MULTIPLIER / 5]

LINE_WIDTH = DIMENSION_MULTIPLIER / 10

FONT_SIZE = DIMENSION_MULTIPLIER / 1.2

PACKET_HEIGHT = DIMENSION_MULTIPLIER * 3

PACKET_GAP_Y = DIMENSION_MULTIPLIER * 4

PACKET_GAP_X = DIMENSION_MULTIPLIER * 5

Y_START = DIMENSION_MULTIPLIER


def get_BITS_OFFSET():
    return DIMENSION_MULTIPLIER / 5
