__title__ = "netbox-mikrotik"
__description__ = "Sync IP-Adresses to Mikrotik Adress Lists and more."
__version__ = "0.1.0.dev1"
__author__ = "Julius Koenig"
__author_email__ = "info@bastelquartier.de"
__license__ = "GPL-3.0"
__license_url__ = "https://www.gnu.org/licenses/gpl-3.0.md"
__terms_of_service__ = "https://bastelquartier.de/terms-of-service"