"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from enum import Enum


class BatteryVendor(str, Enum):
    r"""Machine-friendly name of the vendor. Use this in API requests."""

    TESLA = "TESLA"
    ENPHASE = "ENPHASE"
    GIVENERGY = "GIVENERGY"
    HUAWEI = "HUAWEI"
    SOLAREDGE = "SOLAREDGE"
    SMA = "SMA"
    FOXESS = "FOXESS"
    SOLAX = "SOLAX"
    SOLIS = "SOLIS"
