"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from enode.types import BaseModel
import pydantic
from typing_extensions import Annotated, TypedDict


class TargetMaxCurrentTypedDict(TypedDict):
    r"""Target maximum current for entity"""

    max_current: float
    r"""Desired max current in ampere"""


class TargetMaxCurrent(BaseModel):
    r"""Target maximum current for entity"""

    max_current: Annotated[float, pydantic.Field(alias="maxCurrent")]
    r"""Desired max current in ampere"""
