"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from enum import Enum


class VendorType(str, Enum):
    r"""Only return interventions for the specified vendor type."""

    VEHICLE = "vehicle"
    CHARGER = "charger"
    HVAC = "hvac"
    INVERTER = "inverter"
    BATTERY = "battery"
    METER = "meter"
