
# This file was generated by 'versioneer.py' (0.21) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2025-09-03T19:47:18+0200",
 "dirty": false,
 "error": null,
 "full-revisionid": "aafce1a0b8a11ec6fc39b3a8c5164bc0c80ea6d0",
 "version": "2.7.2"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
