# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: rbt/cloud/v1alpha1/istio/virtual_service.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from rbt.cloud.v1alpha1.istio import virtual_service_spec_pb2 as rbt_dot_cloud_dot_v1alpha1_dot_istio_dot_virtual__service__spec__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n.rbt/cloud/v1alpha1/istio/virtual_service.proto\x12\x18rbt.cloud.v1alpha1.istio\x1a\x33rbt/cloud/v1alpha1/istio/virtual_service_spec.proto\"I\n\x0eVirtualService\x12\x37\n\x04spec\x18\x01 \x01(\x0b\x32).istio.networking.v1alpha3.VirtualServiceb\x06proto3')



_VIRTUALSERVICE = DESCRIPTOR.message_types_by_name['VirtualService']
VirtualService = _reflection.GeneratedProtocolMessageType('VirtualService', (_message.Message,), {
  'DESCRIPTOR' : _VIRTUALSERVICE,
  '__module__' : 'rbt.cloud.v1alpha1.istio.virtual_service_pb2'
  # @@protoc_insertion_point(class_scope:rbt.cloud.v1alpha1.istio.VirtualService)
  })
_sym_db.RegisterMessage(VirtualService)

if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _VIRTUALSERVICE._serialized_start=129
  _VIRTUALSERVICE._serialized_end=202
# @@protoc_insertion_point(module_scope)
