# coding: utf-8

"""
    Canva Connect API

    API for building integrations with Canva via a REST api

    The version of the OpenAPI document: 2024-06-18
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.api.comment_api import CommentApi


class TestCommentApi(unittest.TestCase):
    """CommentApi unit test stubs"""

    def setUp(self) -> None:
        self.api = CommentApi()

    def tearDown(self) -> None:
        pass

    def test_create_comment(self) -> None:
        """Test case for create_comment

        """
        pass

    def test_create_reply(self) -> None:
        """Test case for create_reply

        """
        pass

    def test_create_reply_deprecated(self) -> None:
        """Test case for create_reply_deprecated

        """
        pass

    def test_create_thread(self) -> None:
        """Test case for create_thread

        """
        pass

    def test_get_reply(self) -> None:
        """Test case for get_reply

        """
        pass

    def test_get_thread(self) -> None:
        """Test case for get_thread

        """
        pass

    def test_list_replies(self) -> None:
        """Test case for list_replies

        """
        pass


if __name__ == '__main__':
    unittest.main()
