# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'plover_cat\suggest_dialog.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_suggestDialog(object):
    def setupUi(self, suggestDialog):
        suggestDialog.setObjectName("suggestDialog")
        suggestDialog.resize(814, 217)
        self.horizontalLayout = QtWidgets.QHBoxLayout(suggestDialog)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.formLayout = QtWidgets.QFormLayout()
        self.formLayout.setObjectName("formLayout")
        self.label_6 = QtWidgets.QLabel(suggestDialog)
        self.label_6.setObjectName("label_6")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label_6)
        self.searchType = QtWidgets.QComboBox(suggestDialog)
        self.searchType.setObjectName("searchType")
        self.searchType.addItem("")
        self.searchType.addItem("")
        self.searchType.addItem("")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.searchType)
        self.scowlSize = QtWidgets.QComboBox(suggestDialog)
        self.scowlSize.setObjectName("scowlSize")
        self.scowlSize.addItem("")
        self.scowlSize.setItemText(0, "")
        self.scowlSize.addItem("")
        self.scowlSize.addItem("")
        self.scowlSize.addItem("")
        self.scowlSize.addItem("")
        self.scowlSize.addItem("")
        self.scowlSize.addItem("")
        self.scowlSize.addItem("")
        self.scowlSize.addItem("")
        self.scowlSize.addItem("")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.scowlSize)
        self.label = QtWidgets.QLabel(suggestDialog)
        self.label.setObjectName("label")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.label)
        self.minOccur = QtWidgets.QSpinBox(suggestDialog)
        self.minOccur.setMinimum(1)
        self.minOccur.setProperty("value", 3)
        self.minOccur.setObjectName("minOccur")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.minOccur)
        self.label_2 = QtWidgets.QLabel(suggestDialog)
        self.label_2.setObjectName("label_2")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.label_2)
        self.minNgram = QtWidgets.QSpinBox(suggestDialog)
        self.minNgram.setMinimum(2)
        self.minNgram.setObjectName("minNgram")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.FieldRole, self.minNgram)
        self.label_3 = QtWidgets.QLabel(suggestDialog)
        self.label_3.setObjectName("label_3")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.LabelRole, self.label_3)
        self.maxNgram = QtWidgets.QSpinBox(suggestDialog)
        self.maxNgram.setMinimum(2)
        self.maxNgram.setObjectName("maxNgram")
        self.formLayout.setWidget(4, QtWidgets.QFormLayout.FieldRole, self.maxNgram)
        self.label_7 = QtWidgets.QLabel(suggestDialog)
        self.label_7.setObjectName("label_7")
        self.formLayout.setWidget(4, QtWidgets.QFormLayout.LabelRole, self.label_7)
        self.detect = QtWidgets.QPushButton(suggestDialog)
        self.detect.setObjectName("detect")
        self.formLayout.setWidget(5, QtWidgets.QFormLayout.FieldRole, self.detect)
        self.horizontalLayout_2.addLayout(self.formLayout)
        self.displaySuggest = QtWidgets.QTableWidget(suggestDialog)
        self.displaySuggest.setObjectName("displaySuggest")
        self.displaySuggest.setColumnCount(0)
        self.displaySuggest.setRowCount(0)
        self.horizontalLayout_2.addWidget(self.displaySuggest)
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.toDictionary = QtWidgets.QPushButton(suggestDialog)
        self.toDictionary.setObjectName("toDictionary")
        self.verticalLayout_2.addWidget(self.toDictionary)
        self.buttonBox = QtWidgets.QDialogButtonBox(suggestDialog)
        self.buttonBox.setOrientation(QtCore.Qt.Vertical)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.Close)
        self.buttonBox.setObjectName("buttonBox")
        self.verticalLayout_2.addWidget(self.buttonBox)
        self.horizontalLayout_2.addLayout(self.verticalLayout_2)
        self.horizontalLayout.addLayout(self.horizontalLayout_2)

        self.retranslateUi(suggestDialog)
        self.scowlSize.setCurrentIndex(0)
        self.buttonBox.accepted.connect(suggestDialog.accept) # type: ignore
        self.buttonBox.rejected.connect(suggestDialog.reject) # type: ignore
        QtCore.QMetaObject.connectSlotsByName(suggestDialog)

    def retranslateUi(self, suggestDialog):
        _translate = QtCore.QCoreApplication.translate
        suggestDialog.setWindowTitle(_translate("suggestDialog", "Dialog"))
        self.label_6.setText(_translate("suggestDialog", "Search for:"))
        self.searchType.setItemText(0, _translate("suggestDialog", "N-grams and words"))
        self.searchType.setItemText(1, _translate("suggestDialog", "N-grams only"))
        self.searchType.setItemText(2, _translate("suggestDialog", "Words only"))
        self.scowlSize.setToolTip(_translate("suggestDialog", "Filter for words with size greater than selected in SCOWL. If blank, only filters common stopwords"))
        self.scowlSize.setItemText(1, _translate("suggestDialog", "10"))
        self.scowlSize.setItemText(2, _translate("suggestDialog", "20"))
        self.scowlSize.setItemText(3, _translate("suggestDialog", "35"))
        self.scowlSize.setItemText(4, _translate("suggestDialog", "40"))
        self.scowlSize.setItemText(5, _translate("suggestDialog", "50"))
        self.scowlSize.setItemText(6, _translate("suggestDialog", "55"))
        self.scowlSize.setItemText(7, _translate("suggestDialog", "60"))
        self.scowlSize.setItemText(8, _translate("suggestDialog", "70"))
        self.scowlSize.setItemText(9, _translate("suggestDialog", "80"))
        self.label.setText(_translate("suggestDialog", "SCOWL size filter:"))
        self.minOccur.setToolTip(_translate("suggestDialog", "Word/n-gram must occur at least this many times"))
        self.label_2.setText(_translate("suggestDialog", "Minimum occurrence:"))
        self.minNgram.setToolTip(_translate("suggestDialog", "N-gram must be this many words long"))
        self.label_3.setText(_translate("suggestDialog", "Min n-gram length:"))
        self.maxNgram.setToolTip(_translate("suggestDialog", "N-gram cannot be longer than this value"))
        self.label_7.setText(_translate("suggestDialog", "Max n-gram length:"))
        self.detect.setToolTip(_translate("suggestDialog", "Perform selected search"))
        self.detect.setText(_translate("suggestDialog", "Detect"))
        self.toDictionary.setToolTip(_translate("suggestDialog", "Send selected translation and outline to dictionary"))
        self.toDictionary.setText(_translate("suggestDialog", "To Dictionary"))
