"""
db4e/Constants/Labels.py

    Database 4 Everything
    Author: Nadim-Daniel Ghaznavi 
    Copyright: (c) 2024-2025 Nadim-Daniel Ghaznavi
    GitHub: https://github.com/NadimGhaznavi/db4e
    License: GPL 3.0
"""

ANY_IP_LABEL = "Listen on IP"
API_LABEL = "API"
CHAIN_LABEL = "Chain"
CONFIG_LABEL = "Configuration"
CONFIG_FILE_LABLE = "Configuration File"
DATA_DIR_LABEL = "Blockchain Directory"
DB4E_LABEL = "Db4E Core"
DB4E_LONG_LABEL = "Database 4 Everything"
DB4E_GROUP_LABEL = "Db4E Group"
DB4E_USER_LABEL = "Db4E User"
DEPLOYMENTS_LABEL = "Deployments"
DONATIONS_LABEL = "Donations"
DONATIONS_WALLET_LABEL = "Donations Wallet"
GROUP_LABEL = "Group"
HEALTH_LABEL = "Health Checks"
HEALTH_MSGS_LABEL = "Health Checks"
IN_PEERS_LABEL = "Incoming Peer Connections"
INITIAL_SETUP_LABEL = "Initial Setup"
INSTALL_DIR_LABEL = "Install Directory"
INSTANCE_LABEL = "Instance"
IP_ADDR_LABEL = "Hostname/IP Address"
LOCAL_SOFTWARE_SYSTEM_LABEL = "Local Software System"
LOG_LABEL = "Log"
LOG_LEVEL_LABEL = "Log Level"
LOG_FILE_LABEL = "Log File"
LOG_VIEWER_LABEL = "Log Viewer"
MACHINE_LABEL = "Host"
MAX_LOG_FILES_LABEL = "Maximum Number of Log Files"
MAX_LOG_SIZE_LABEL = "Maximum Log File Size"
METRICS_LABEL = "Metrics"
MONEROD_LABEL = "Monero Daemon"
MONEROD_REMOTE_LABEL = "Remote Monero Daemon"
MONEROD_SHORT_LABEL = "Monero"
NUM_THREADS_LABEL = "Number of Threads"
OBJECT_ID_LABEL = "Object ID"
OPS_MGR_LABEL = "Ops Manager"
OUT_PEERS_LABEL = "Outgoing Peer Connections"
P2P_BIND_PORT_LABEL = "P2P Bind Port"
P2POOL_LABEL = "P2Pool Daemon"
P2POOL_REMOTE_LABEL = "Remote P2Pool Daemon"
P2POOL_SHORT_LABEL = "P2Pool"
PARENT_LABEL = "Parent"
PARENT_ID_LABEL = "Parent ID"
PRIORITY_NODE_1_LABEL = "Priority Node 1"
PRIORITY_NODE_2_LABEL = "Priority Node 2"
PRIORITY_PORT_1_LABEL = "Priority Port 1"
PRIORITY_PORT_2_LABEL = "Priority Port 2"
REMOTE_LABEL = "Remote"
RESULTS_LABEL = "Results"
RPC_BIND_PORT_LABEL = "RPC Bind Port"
SHOW_TIME_STATS_LABEL = "Show Time Stats"
SOFTWARE_SYSTEM_LABEL = "Software System"
START_LABEL = "Start"
STARTUP_SCRIPT = "Startup Script"
STOP_LABEL = "Stop"
STRATUM_PORT_LABEL = "Stratum Port"
TUI_LOG_LABEL = "Console Log"
USER_LABEL = "User"
USER_WALLET_LABEL = "Monero User Wallet"
VENDOR_DIR_LABEL = "Deployment Directory"
VERSION_LABEL = "Version"
WELCOME_LABEL = "Welcome"
WALLET_LABEL = "Monero Wallet"
XMRIG_LABEL = "XMRig Miner"
XMRIG_SHORT_LABEL = "XMRig"
ZMQ_PUB_PORT_LABEL = "ZMQ Pub Port"
ZMQ_RPC_PORT_LABEL = "ZMQ RPC Port"

