# Constants for the repository

import numpy as np

DEFAULT_SR: int = 22050
DEFAULT_HOP_LENGTH: int = 512
DEFAULT_FEATURE_WINDOW: int = 2048
DEFAULT_CHUNK_SIZE_NOA: int = 1024
DEFAULT_CHUNK_SIZE_TSM: int = 2048
DEFAULT_ALPHA_UPDATE_FREQUENCY: int = 10
DEFAULT_ALPHA_LOOKBACK: int = 100
DEFAULT_ALPHA_ADJUST_FREQUENCY: int = 2
DEFAULT_MAX_TIMEWARP_FACTOR: float = 2.0
DEFAULT_MAX_TSM_FACTOR: float = 1.3
DEFAULT_ALPHA_ADJUST_SENSITIVITY: float = 0.08
DEFAULT_ALPHA_ADJUST_MAX_SCALE: float = 1.3
DEFAULT_ALPHA_ADJUST_MIN_SCALE: float = 1 / DEFAULT_ALPHA_ADJUST_MAX_SCALE
DEFAULT_INITIAL_CONSTANT_PERIOD: int = 10

DEFAULT_DTW_STEPS: np.ndarray = np.array([1, 1, 1, 2, 2, 1]).reshape((-1, 2))
DEFAULT_DTW_WEIGHTS: np.ndarray = np.array([1, 1, 2])
