# coding: utf-8

"""
    Neurograph Core2

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.models.organizations_organization_set_atlas_response import OrganizationsOrganizationSetAtlasResponse

class TestOrganizationsOrganizationSetAtlasResponse(unittest.TestCase):
    """OrganizationsOrganizationSetAtlasResponse unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> OrganizationsOrganizationSetAtlasResponse:
        """Test OrganizationsOrganizationSetAtlasResponse
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `OrganizationsOrganizationSetAtlasResponse`
        """
        model = OrganizationsOrganizationSetAtlasResponse()
        if include_optional:
            return OrganizationsOrganizationSetAtlasResponse(
                description = '',
                error = '',
                id = 56,
                is_active = True,
                name = '',
                url = '',
                version = ''
            )
        else:
            return OrganizationsOrganizationSetAtlasResponse(
        )
        """

    def testOrganizationsOrganizationSetAtlasResponse(self):
        """Test OrganizationsOrganizationSetAtlasResponse"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
