# coding: utf-8

"""
    Neurograph Core2

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.api.tasks_api import TasksApi


class TestTasksApi(unittest.TestCase):
    """TasksApi unit test stubs"""

    def setUp(self) -> None:
        self.api = TasksApi()

    def tearDown(self) -> None:
        pass

    def test_api_v1_tasks_sync_from_firebase_get(self) -> None:
        """Test case for api_v1_tasks_sync_from_firebase_get

        Trigger Sync From Firebase
        """
        pass


if __name__ == '__main__':
    unittest.main()
