from _typeshed import Incomplete
from minio import Minio
from minjiang_client.com.oss import get_global as get_global
from typing import Any

OSS_CONFIG: Incomplete
oss_config: Incomplete

class MinIOAPI:
    config: dict
    client: Minio | None
    def __init__(self) -> None: ...
    def open_client(self) -> None: ...
    def upload(self, indicator: Any, data: Any, file_cate: str, file_format: str) -> dict: ...
    def upload_normal(self, obj_key: str, file_name: str) -> dict: ...
    def download(self, uri: dict | str) -> Any: ...
    def download_to_file(self, uri: dict | str, path: str): ...
    def presign(self, uri: dict | str, expiry_hour: int = 2): ...
