from minjiang_client.com.request import request as request

def set_oss_auth(if_global: bool, user_id: int = None, auth_text: str = None, disabled: bool = False): ...
def get_user_auth_text(user_id: int): ...
def get_global(user_id: int = None): ...
def get_resource_info(resource_id_list: list): ...
def add_resource(file_name: str, file_format: str, uri: str, file_type: str, source: str): ...
