"""Base domain layer - shared kernel for all bounded contexts."""

from .domain_interfaces import (
    AggregateRepository,
    Repository,
    RepositoryProtocol,
    UnitOfWork,
    UnitOfWorkFactory,
)
from .entity import AggregateRoot, Entity
from .events import (  # Request Events; Machine Events; Template Events; Infrastructure Events
    DomainEvent,
    EventPublisher,
    InfrastructureEvent,
    MachineCreatedEvent,
    MachineEvent,
    MachineHealthCheckEvent,
    MachineProvisionedEvent,
    MachineStatusChangedEvent,
    MachineTerminatedEvent,
    OperationCompletedEvent,
    OperationFailedEvent,
    OperationStartedEvent,
    RequestCompletedEvent,
    RequestCreatedEvent,
    RequestEvent,
    RequestFailedEvent,
    RequestStatusChangedEvent,
    RequestTimeoutEvent,
    ResourceCreatedEvent,
    ResourceDeletedEvent,
    ResourceErrorEvent,
    ResourceEvent,
    ResourceUpdatedEvent,
    TemplateCreatedEvent,
    TemplateDeletedEvent,
    TemplateEvent,
    TemplateUpdatedEvent,
    TemplateValidatedEvent,
)
from .exceptions import (
    BusinessRuleViolationError,
    ConcurrencyError,
    ConfigurationError,
    DomainException,
    EntityNotFoundError,
    InfrastructureError,
    InvariantViolationError,
    ValidationError,
)
from .value_objects import (
    ARN,
    AllocationStrategy,
    InstanceId,
    InstanceType,
    IPAddress,
    PriceType,
    ResourceId,
    Tags,
    ValueObject,
)

__all__: list[str] = [
    "ARN",
    "AggregateRepository",
    "AggregateRoot",
    "AllocationStrategy",
    "BusinessRuleViolationError",
    "ConcurrencyError",
    "ConfigurationError",
    # Events
    "DomainEvent",
    "InfrastructureEvent",
    "MachineCreatedEvent",
    "MachineEvent",
    "MachineHealthCheckEvent",
    "MachineProvisionedEvent",
    "MachineStatusChangedEvent",
    "MachineTerminatedEvent",
    "OperationCompletedEvent",
    "OperationFailedEvent",
    "OperationStartedEvent",
    "RequestCompletedEvent",
    "RequestCreatedEvent",
    "RequestEvent",
    "RequestFailedEvent",
    "RequestStatusChangedEvent",
    "RequestTimeoutEvent",
    "ResourceCreatedEvent",
    "ResourceDeletedEvent",
    "ResourceErrorEvent",
    "ResourceEvent",
    "ResourceUpdatedEvent",
    "TemplateCreatedEvent",
    "TemplateDeletedEvent",
    "TemplateEvent",
    "TemplateUpdatedEvent",
    "TemplateValidatedEvent",
    # Exceptions
    "DomainException",
    # Entities
    "Entity",
    "EntityNotFoundError",
    "EventPublisher",
    "IPAddress",
    "IRepository",
    "IUnitOfWork",
    "InfrastructureError",
    "InfrastructureEvent",
    "InstanceId",
    "InstanceType",
    "InvariantViolationError",
    "PriceType",
    # Repository
    "Repository",
    # Domain Interfaces (clean)
    "RepositoryProtocol",
    "ResourceId",
    "Tags",
    "UnitOfWork",
    "UnitOfWorkFactory",
    "ValidationError",
    # Value Objects
    "ValueObject",
]
