# Generated by Django 5.2.5 on 2025-08-26 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("netbox_custom_objects", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="customobjecttype",
            name="version",
            field=models.CharField(blank=True, max_length=10),
        ),
    ]
