# coding: utf-8

"""
    LOCKSS Repository Service REST API

    REST API of the LOCKSS Repository Service  # noqa: E501

    OpenAPI spec version: 2.0.0
    Contact: lockss-support@lockss.org
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six

class RepositoryStatistics(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'time_spent_reiterating_iterators': 'int'
    }

    attribute_map = {
        'time_spent_reiterating_iterators': 'timeSpentReiteratingIterators'
    }

    def __init__(self, time_spent_reiterating_iterators=None):  # noqa: E501
        """RepositoryStatistics - a model defined in Swagger"""  # noqa: E501
        self._time_spent_reiterating_iterators = None
        self.discriminator = None
        if time_spent_reiterating_iterators is not None:
            self.time_spent_reiterating_iterators = time_spent_reiterating_iterators

    @property
    def time_spent_reiterating_iterators(self):
        """Gets the time_spent_reiterating_iterators of this RepositoryStatistics.  # noqa: E501

        Time spent reiterating a new artifact iterator during continuation.  # noqa: E501

        :return: The time_spent_reiterating_iterators of this RepositoryStatistics.  # noqa: E501
        :rtype: int
        """
        return self._time_spent_reiterating_iterators

    @time_spent_reiterating_iterators.setter
    def time_spent_reiterating_iterators(self, time_spent_reiterating_iterators):
        """Sets the time_spent_reiterating_iterators of this RepositoryStatistics.

        Time spent reiterating a new artifact iterator during continuation.  # noqa: E501

        :param time_spent_reiterating_iterators: The time_spent_reiterating_iterators of this RepositoryStatistics.  # noqa: E501
        :type: int
        """

        self._time_spent_reiterating_iterators = time_spent_reiterating_iterators

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(RepositoryStatistics, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, RepositoryStatistics):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
