"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from outpost_sdk.types import BaseModel
from typing import Optional
from typing_extensions import NotRequired, TypedDict


class Awss3CredentialsTypedDict(TypedDict):
    key: str
    r"""AWS Access Key ID."""
    secret: str
    r"""AWS Secret Access Key."""
    session: NotRequired[str]
    r"""Optional AWS Session Token (for temporary credentials)."""


class Awss3Credentials(BaseModel):
    key: str
    r"""AWS Access Key ID."""

    secret: str
    r"""AWS Secret Access Key."""

    session: Optional[str] = None
    r"""Optional AWS Session Token (for temporary credentials)."""
