"""
@generated by mypy-protobuf.  Do not edit manually!
isort:skip_file
"""
import builtins
import google.protobuf.descriptor
import google.protobuf.internal.enum_type_wrapper
import google.protobuf.message
import sys
import typing

if sys.version_info >= (3, 10):
    import typing as typing_extensions
else:
    import typing_extensions

DESCRIPTOR: google.protobuf.descriptor.FileDescriptor

@typing_extensions.final
class Online(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    class _TimeToLiveInterval:
        ValueType = typing.NewType("ValueType", builtins.int)
        V: typing_extensions.TypeAlias = ValueType

    class _TimeToLiveIntervalEnumTypeWrapper(google.protobuf.internal.enum_type_wrapper._EnumTypeWrapper[Online._TimeToLiveInterval.ValueType], builtins.type):
        DESCRIPTOR: google.protobuf.descriptor.EnumDescriptor
        DAYS: Online._TimeToLiveInterval.ValueType  # 0
        """value with 0 is default one"""
        MONTHS: Online._TimeToLiveInterval.ValueType  # 1
        HOURS: Online._TimeToLiveInterval.ValueType  # 2
        MINUTES: Online._TimeToLiveInterval.ValueType  # 3

    class TimeToLiveInterval(_TimeToLiveInterval, metaclass=_TimeToLiveIntervalEnumTypeWrapper): ...
    DAYS: Online.TimeToLiveInterval.ValueType  # 0
    """value with 0 is default one"""
    MONTHS: Online.TimeToLiveInterval.ValueType  # 1
    HOURS: Online.TimeToLiveInterval.ValueType  # 2
    MINUTES: Online.TimeToLiveInterval.ValueType  # 3

    def __init__(
        self,
    ) -> None: ...

global___Online = Online

@typing_extensions.final
class Offline(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    class _TimeToLiveInterval:
        ValueType = typing.NewType("ValueType", builtins.int)
        V: typing_extensions.TypeAlias = ValueType

    class _TimeToLiveIntervalEnumTypeWrapper(google.protobuf.internal.enum_type_wrapper._EnumTypeWrapper[Offline._TimeToLiveInterval.ValueType], builtins.type):
        DESCRIPTOR: google.protobuf.descriptor.EnumDescriptor
        YEARS: Offline._TimeToLiveInterval.ValueType  # 0
        """value with 0 is default one"""
        DAYS: Offline._TimeToLiveInterval.ValueType  # 1
        MONTHS: Offline._TimeToLiveInterval.ValueType  # 2
        HOURS: Offline._TimeToLiveInterval.ValueType  # 3

    class TimeToLiveInterval(_TimeToLiveInterval, metaclass=_TimeToLiveIntervalEnumTypeWrapper): ...
    YEARS: Offline.TimeToLiveInterval.ValueType  # 0
    """value with 0 is default one"""
    DAYS: Offline.TimeToLiveInterval.ValueType  # 1
    MONTHS: Offline.TimeToLiveInterval.ValueType  # 2
    HOURS: Offline.TimeToLiveInterval.ValueType  # 3

    def __init__(
        self,
    ) -> None: ...

global___Offline = Offline

@typing_extensions.final
class TimeToLive(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    TTL_OFFLINE_FIELD_NUMBER: builtins.int
    TTL_OFFLINE_INTERVAL_FIELD_NUMBER: builtins.int
    TTL_ONLINE_FIELD_NUMBER: builtins.int
    TTL_ONLINE_INTERVAL_FIELD_NUMBER: builtins.int
    ttl_offline: builtins.int
    ttl_offline_interval: global___Offline.TimeToLiveInterval.ValueType
    ttl_online: builtins.int
    ttl_online_interval: global___Online.TimeToLiveInterval.ValueType
    def __init__(
        self,
        *,
        ttl_offline: builtins.int = ...,
        ttl_offline_interval: global___Offline.TimeToLiveInterval.ValueType = ...,
        ttl_online: builtins.int = ...,
        ttl_online_interval: global___Online.TimeToLiveInterval.ValueType = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing_extensions.Literal["ttl_offline", b"ttl_offline", "ttl_offline_interval", b"ttl_offline_interval", "ttl_online", b"ttl_online", "ttl_online_interval", b"ttl_online_interval"]) -> None: ...

global___TimeToLive = TimeToLive
